"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from sunsynk_api_client.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .batterydata import BatteryData, BatteryDataTypedDict
    from .batteryresponse import BatteryResponse, BatteryResponseTypedDict
    from .gatewayinfo import GatewayInfo, GatewayInfoTypedDict
    from .get_api_v1_invertersop import (
        GetAPIV1InvertersRequest,
        GetAPIV1InvertersRequestTypedDict,
    )
    from .getbatteryrealtimeop import (
        GetBatteryRealtimeRequest,
        GetBatteryRealtimeRequestTypedDict,
    )
    from .getbearertokenop import (
        GetBearerTokenData,
        GetBearerTokenDataTypedDict,
        GetBearerTokenRequest,
        GetBearerTokenRequestTypedDict,
        GetBearerTokenResponse,
        GetBearerTokenResponseTypedDict,
    )
    from .geteventsop import (
        GetEventsRequest,
        GetEventsRequestTypedDict,
        GetEventsResponse,
        GetEventsResponseTypedDict,
    )
    from .getgatewaysop import (
        GetGatewaysRequest,
        GetGatewaysRequestTypedDict,
        GetGatewaysResponse,
        GetGatewaysResponseTypedDict,
    )
    from .getgenrealtimeop import (
        GetGenRealtimeRequest,
        GetGenRealtimeRequestTypedDict,
        GetGenRealtimeResponse,
        GetGenRealtimeResponseTypedDict,
    )
    from .getgridrealtimeop import (
        GetGridRealtimeRequest,
        GetGridRealtimeRequestTypedDict,
    )
    from .getinverterdailyoutputop import (
        GetInverterDailyOutputRequest,
        GetInverterDailyOutputRequestTypedDict,
        GetInverterDailyOutputResponse,
        GetInverterDailyOutputResponseTypedDict,
    )
    from .getinverterinputop import (
        GetInverterInputRequest,
        GetInverterInputRequestTypedDict,
    )
    from .getinverteroutputop import (
        GetInverterOutputRequest,
        GetInverterOutputRequestTypedDict,
    )
    from .getloadrealtimeop import (
        GetLoadRealtimeRequest,
        GetLoadRealtimeRequestTypedDict,
        GetLoadRealtimeResponse,
        GetLoadRealtimeResponseTypedDict,
    )
    from .getmessagesop import (
        GetMessagesRequest,
        GetMessagesRequestTypedDict,
        GetMessagesResponse,
        GetMessagesResponseTypedDict,
    )
    from .getplantflowop import (
        GetPlantFlowRequest,
        GetPlantFlowRequestTypedDict,
        GetPlantFlowResponse,
        GetPlantFlowResponseTypedDict,
    )
    from .getplantinvertersop import (
        GetPlantInvertersRequest,
        GetPlantInvertersRequestTypedDict,
        GetPlantInvertersResponse,
        GetPlantInvertersResponseTypedDict,
    )
    from .getplantsop import GetPlantsRequest, GetPlantsRequestTypedDict
    from .getpublickeyop import (
        GetPublicKeyRequest,
        GetPublicKeyRequestTypedDict,
        GetPublicKeyResponse,
        GetPublicKeyResponseTypedDict,
    )
    from .griddata import GridData, GridDataTypedDict
    from .gridresponse import GridResponse, GridResponseTypedDict
    from .inputdata import InputData, InputDataTypedDict
    from .inputresponse import InputResponse, InputResponseTypedDict
    from .inverter import Inverter, InverterTypedDict
    from .invertersresponse import (
        InvertersResponse,
        InvertersResponseData,
        InvertersResponseDataTypedDict,
        InvertersResponseTypedDict,
    )
    from .inverterversion import InverterVersion, InverterVersionTypedDict
    from .outputdata import OutputData, OutputDataTypedDict
    from .outputresponse import OutputResponse, OutputResponseTypedDict
    from .plant import Plant, PlantTypedDict
    from .plantsresponse import (
        PlantsResponse,
        PlantsResponseData,
        PlantsResponseDataTypedDict,
        PlantsResponseTypedDict,
    )
    from .plantsummary import PlantSummary, PlantSummaryTypedDict
    from .pviv import PvIv, PvIvTypedDict
    from .readinvertersettingsop import (
        ReadInverterSettingsRequest,
        ReadInverterSettingsRequestTypedDict,
        ReadInverterSettingsResponse,
        ReadInverterSettingsResponseTypedDict,
    )
    from .security import Security, SecurityTypedDict
    from .tokenrequest import ClientID, GrantType, TokenRequest, TokenRequestTypedDict
    from .tokenresponse import (
        TokenResponse,
        TokenResponseData,
        TokenResponseDataTypedDict,
        TokenResponseTypedDict,
    )
    from .vip import Vip, VipTypedDict
    from .writeinvertersettingsop import (
        WriteInverterSettingsRequest,
        WriteInverterSettingsRequestBody,
        WriteInverterSettingsRequestBodyTypedDict,
        WriteInverterSettingsRequestTypedDict,
        WriteInverterSettingsResponse,
        WriteInverterSettingsResponseTypedDict,
    )

__all__ = [
    "BatteryData",
    "BatteryDataTypedDict",
    "BatteryResponse",
    "BatteryResponseTypedDict",
    "ClientID",
    "GatewayInfo",
    "GatewayInfoTypedDict",
    "GetAPIV1InvertersRequest",
    "GetAPIV1InvertersRequestTypedDict",
    "GetBatteryRealtimeRequest",
    "GetBatteryRealtimeRequestTypedDict",
    "GetBearerTokenData",
    "GetBearerTokenDataTypedDict",
    "GetBearerTokenRequest",
    "GetBearerTokenRequestTypedDict",
    "GetBearerTokenResponse",
    "GetBearerTokenResponseTypedDict",
    "GetEventsRequest",
    "GetEventsRequestTypedDict",
    "GetEventsResponse",
    "GetEventsResponseTypedDict",
    "GetGatewaysRequest",
    "GetGatewaysRequestTypedDict",
    "GetGatewaysResponse",
    "GetGatewaysResponseTypedDict",
    "GetGenRealtimeRequest",
    "GetGenRealtimeRequestTypedDict",
    "GetGenRealtimeResponse",
    "GetGenRealtimeResponseTypedDict",
    "GetGridRealtimeRequest",
    "GetGridRealtimeRequestTypedDict",
    "GetInverterDailyOutputRequest",
    "GetInverterDailyOutputRequestTypedDict",
    "GetInverterDailyOutputResponse",
    "GetInverterDailyOutputResponseTypedDict",
    "GetInverterInputRequest",
    "GetInverterInputRequestTypedDict",
    "GetInverterOutputRequest",
    "GetInverterOutputRequestTypedDict",
    "GetLoadRealtimeRequest",
    "GetLoadRealtimeRequestTypedDict",
    "GetLoadRealtimeResponse",
    "GetLoadRealtimeResponseTypedDict",
    "GetMessagesRequest",
    "GetMessagesRequestTypedDict",
    "GetMessagesResponse",
    "GetMessagesResponseTypedDict",
    "GetPlantFlowRequest",
    "GetPlantFlowRequestTypedDict",
    "GetPlantFlowResponse",
    "GetPlantFlowResponseTypedDict",
    "GetPlantInvertersRequest",
    "GetPlantInvertersRequestTypedDict",
    "GetPlantInvertersResponse",
    "GetPlantInvertersResponseTypedDict",
    "GetPlantsRequest",
    "GetPlantsRequestTypedDict",
    "GetPublicKeyRequest",
    "GetPublicKeyRequestTypedDict",
    "GetPublicKeyResponse",
    "GetPublicKeyResponseTypedDict",
    "GrantType",
    "GridData",
    "GridDataTypedDict",
    "GridResponse",
    "GridResponseTypedDict",
    "InputData",
    "InputDataTypedDict",
    "InputResponse",
    "InputResponseTypedDict",
    "Inverter",
    "InverterTypedDict",
    "InverterVersion",
    "InverterVersionTypedDict",
    "InvertersResponse",
    "InvertersResponseData",
    "InvertersResponseDataTypedDict",
    "InvertersResponseTypedDict",
    "OutputData",
    "OutputDataTypedDict",
    "OutputResponse",
    "OutputResponseTypedDict",
    "Plant",
    "PlantSummary",
    "PlantSummaryTypedDict",
    "PlantTypedDict",
    "PlantsResponse",
    "PlantsResponseData",
    "PlantsResponseDataTypedDict",
    "PlantsResponseTypedDict",
    "PvIv",
    "PvIvTypedDict",
    "ReadInverterSettingsRequest",
    "ReadInverterSettingsRequestTypedDict",
    "ReadInverterSettingsResponse",
    "ReadInverterSettingsResponseTypedDict",
    "Security",
    "SecurityTypedDict",
    "TokenRequest",
    "TokenRequestTypedDict",
    "TokenResponse",
    "TokenResponseData",
    "TokenResponseDataTypedDict",
    "TokenResponseTypedDict",
    "Vip",
    "VipTypedDict",
    "WriteInverterSettingsRequest",
    "WriteInverterSettingsRequestBody",
    "WriteInverterSettingsRequestBodyTypedDict",
    "WriteInverterSettingsRequestTypedDict",
    "WriteInverterSettingsResponse",
    "WriteInverterSettingsResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "BatteryData": ".batterydata",
    "BatteryDataTypedDict": ".batterydata",
    "BatteryResponse": ".batteryresponse",
    "BatteryResponseTypedDict": ".batteryresponse",
    "GatewayInfo": ".gatewayinfo",
    "GatewayInfoTypedDict": ".gatewayinfo",
    "GetAPIV1InvertersRequest": ".get_api_v1_invertersop",
    "GetAPIV1InvertersRequestTypedDict": ".get_api_v1_invertersop",
    "GetBatteryRealtimeRequest": ".getbatteryrealtimeop",
    "GetBatteryRealtimeRequestTypedDict": ".getbatteryrealtimeop",
    "GetBearerTokenData": ".getbearertokenop",
    "GetBearerTokenDataTypedDict": ".getbearertokenop",
    "GetBearerTokenRequest": ".getbearertokenop",
    "GetBearerTokenRequestTypedDict": ".getbearertokenop",
    "GetBearerTokenResponse": ".getbearertokenop",
    "GetBearerTokenResponseTypedDict": ".getbearertokenop",
    "GetEventsRequest": ".geteventsop",
    "GetEventsRequestTypedDict": ".geteventsop",
    "GetEventsResponse": ".geteventsop",
    "GetEventsResponseTypedDict": ".geteventsop",
    "GetGatewaysRequest": ".getgatewaysop",
    "GetGatewaysRequestTypedDict": ".getgatewaysop",
    "GetGatewaysResponse": ".getgatewaysop",
    "GetGatewaysResponseTypedDict": ".getgatewaysop",
    "GetGenRealtimeRequest": ".getgenrealtimeop",
    "GetGenRealtimeRequestTypedDict": ".getgenrealtimeop",
    "GetGenRealtimeResponse": ".getgenrealtimeop",
    "GetGenRealtimeResponseTypedDict": ".getgenrealtimeop",
    "GetGridRealtimeRequest": ".getgridrealtimeop",
    "GetGridRealtimeRequestTypedDict": ".getgridrealtimeop",
    "GetInverterDailyOutputRequest": ".getinverterdailyoutputop",
    "GetInverterDailyOutputRequestTypedDict": ".getinverterdailyoutputop",
    "GetInverterDailyOutputResponse": ".getinverterdailyoutputop",
    "GetInverterDailyOutputResponseTypedDict": ".getinverterdailyoutputop",
    "GetInverterInputRequest": ".getinverterinputop",
    "GetInverterInputRequestTypedDict": ".getinverterinputop",
    "GetInverterOutputRequest": ".getinverteroutputop",
    "GetInverterOutputRequestTypedDict": ".getinverteroutputop",
    "GetLoadRealtimeRequest": ".getloadrealtimeop",
    "GetLoadRealtimeRequestTypedDict": ".getloadrealtimeop",
    "GetLoadRealtimeResponse": ".getloadrealtimeop",
    "GetLoadRealtimeResponseTypedDict": ".getloadrealtimeop",
    "GetMessagesRequest": ".getmessagesop",
    "GetMessagesRequestTypedDict": ".getmessagesop",
    "GetMessagesResponse": ".getmessagesop",
    "GetMessagesResponseTypedDict": ".getmessagesop",
    "GetPlantFlowRequest": ".getplantflowop",
    "GetPlantFlowRequestTypedDict": ".getplantflowop",
    "GetPlantFlowResponse": ".getplantflowop",
    "GetPlantFlowResponseTypedDict": ".getplantflowop",
    "GetPlantInvertersRequest": ".getplantinvertersop",
    "GetPlantInvertersRequestTypedDict": ".getplantinvertersop",
    "GetPlantInvertersResponse": ".getplantinvertersop",
    "GetPlantInvertersResponseTypedDict": ".getplantinvertersop",
    "GetPlantsRequest": ".getplantsop",
    "GetPlantsRequestTypedDict": ".getplantsop",
    "GetPublicKeyRequest": ".getpublickeyop",
    "GetPublicKeyRequestTypedDict": ".getpublickeyop",
    "GetPublicKeyResponse": ".getpublickeyop",
    "GetPublicKeyResponseTypedDict": ".getpublickeyop",
    "GridData": ".griddata",
    "GridDataTypedDict": ".griddata",
    "GridResponse": ".gridresponse",
    "GridResponseTypedDict": ".gridresponse",
    "InputData": ".inputdata",
    "InputDataTypedDict": ".inputdata",
    "InputResponse": ".inputresponse",
    "InputResponseTypedDict": ".inputresponse",
    "Inverter": ".inverter",
    "InverterTypedDict": ".inverter",
    "InvertersResponse": ".invertersresponse",
    "InvertersResponseData": ".invertersresponse",
    "InvertersResponseDataTypedDict": ".invertersresponse",
    "InvertersResponseTypedDict": ".invertersresponse",
    "InverterVersion": ".inverterversion",
    "InverterVersionTypedDict": ".inverterversion",
    "OutputData": ".outputdata",
    "OutputDataTypedDict": ".outputdata",
    "OutputResponse": ".outputresponse",
    "OutputResponseTypedDict": ".outputresponse",
    "Plant": ".plant",
    "PlantTypedDict": ".plant",
    "PlantsResponse": ".plantsresponse",
    "PlantsResponseData": ".plantsresponse",
    "PlantsResponseDataTypedDict": ".plantsresponse",
    "PlantsResponseTypedDict": ".plantsresponse",
    "PlantSummary": ".plantsummary",
    "PlantSummaryTypedDict": ".plantsummary",
    "PvIv": ".pviv",
    "PvIvTypedDict": ".pviv",
    "ReadInverterSettingsRequest": ".readinvertersettingsop",
    "ReadInverterSettingsRequestTypedDict": ".readinvertersettingsop",
    "ReadInverterSettingsResponse": ".readinvertersettingsop",
    "ReadInverterSettingsResponseTypedDict": ".readinvertersettingsop",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "ClientID": ".tokenrequest",
    "GrantType": ".tokenrequest",
    "TokenRequest": ".tokenrequest",
    "TokenRequestTypedDict": ".tokenrequest",
    "TokenResponse": ".tokenresponse",
    "TokenResponseData": ".tokenresponse",
    "TokenResponseDataTypedDict": ".tokenresponse",
    "TokenResponseTypedDict": ".tokenresponse",
    "Vip": ".vip",
    "VipTypedDict": ".vip",
    "WriteInverterSettingsRequest": ".writeinvertersettingsop",
    "WriteInverterSettingsRequestBody": ".writeinvertersettingsop",
    "WriteInverterSettingsRequestBodyTypedDict": ".writeinvertersettingsop",
    "WriteInverterSettingsRequestTypedDict": ".writeinvertersettingsop",
    "WriteInverterSettingsResponse": ".writeinvertersettingsop",
    "WriteInverterSettingsResponseTypedDict": ".writeinvertersettingsop",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
