"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from sunsynk_api_client.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .batterydata import BatteryData, BatteryDataTypedDict
    from .batteryresponse import BatteryResponse, BatteryResponseTypedDict
    from .dailyoutputresponse import (
        DailyOutputResponse,
        DailyOutputResponseData,
        DailyOutputResponseDataTypedDict,
        DailyOutputResponseInfo,
        DailyOutputResponseInfoTypedDict,
        DailyOutputResponseTypedDict,
    )
    from .eventsresponse import (
        EventsResponse,
        EventsResponseData,
        EventsResponseDataTypedDict,
        EventsResponseTypedDict,
        Record,
        RecordTypedDict,
    )
    from .gatewayextendedinfo import GatewayExtendedInfo, GatewayExtendedInfoTypedDict
    from .gatewayinfo import GatewayInfo, GatewayInfoTypedDict
    from .gatewaysresponse import (
        GatewaysResponse,
        GatewaysResponseData,
        GatewaysResponseDataTypedDict,
        GatewaysResponseTypedDict,
    )
    from .genrealtimedata import GenRealtimeData, GenRealtimeDataTypedDict
    from .genrealtimeresponse import GenRealtimeResponse, GenRealtimeResponseTypedDict
    from .get_api_v1_invertersop import (
        GetAPIV1InvertersRequest,
        GetAPIV1InvertersRequestTypedDict,
    )
    from .getbatteryrealtimeop import (
        GetBatteryRealtimeRequest,
        GetBatteryRealtimeRequestTypedDict,
    )
    from .getbearertokenop import (
        GetBearerTokenData,
        GetBearerTokenDataTypedDict,
        GetBearerTokenRequest,
        GetBearerTokenRequestTypedDict,
        GetBearerTokenResponse,
        GetBearerTokenResponseTypedDict,
    )
    from .geteventsop import GetEventsRequest, GetEventsRequestTypedDict
    from .getgatewaysop import GetGatewaysRequest, GetGatewaysRequestTypedDict
    from .getgenrealtimeop import GetGenRealtimeRequest, GetGenRealtimeRequestTypedDict
    from .getgridrealtimeop import (
        GetGridRealtimeRequest,
        GetGridRealtimeRequestTypedDict,
    )
    from .getinverterdailyoutputop import (
        GetInverterDailyOutputRequest,
        GetInverterDailyOutputRequestTypedDict,
    )
    from .getinverterinputop import (
        GetInverterInputRequest,
        GetInverterInputRequestTypedDict,
    )
    from .getinverteroutputop import (
        GetInverterOutputRequest,
        GetInverterOutputRequestTypedDict,
    )
    from .getloadrealtimeop import (
        GetLoadRealtimeRequest,
        GetLoadRealtimeRequestTypedDict,
    )
    from .getmessagesop import GetMessagesRequest, GetMessagesRequestTypedDict
    from .getplantflowop import GetPlantFlowRequest, GetPlantFlowRequestTypedDict
    from .getplantinvertersop import (
        GetPlantInvertersRequest,
        GetPlantInvertersRequestTypedDict,
    )
    from .getplantsop import GetPlantsRequest, GetPlantsRequestTypedDict
    from .getpublickeyop import (
        GetPublicKeyRequest,
        GetPublicKeyRequestTypedDict,
        GetPublicKeyResponse,
        GetPublicKeyResponseTypedDict,
    )
    from .griddata import GridData, GridDataTypedDict
    from .gridresponse import GridResponse, GridResponseTypedDict
    from .inputdata import InputData, InputDataTypedDict
    from .inputresponse import InputResponse, InputResponseTypedDict
    from .inverter import Inverter, InverterTypedDict
    from .invertersettings import InverterSettings, InverterSettingsTypedDict
    from .invertersettingsresponse import (
        InverterSettingsResponse,
        InverterSettingsResponseTypedDict,
    )
    from .invertersresponse import (
        InvertersResponse,
        InvertersResponseData,
        InvertersResponseDataTypedDict,
        InvertersResponseTypedDict,
    )
    from .inverterversion import InverterVersion, InverterVersionTypedDict
    from .loadrealtimedata import LoadRealtimeData, LoadRealtimeDataTypedDict
    from .loadrealtimeresponse import (
        LoadRealtimeResponse,
        LoadRealtimeResponseTypedDict,
    )
    from .messagesresponse import (
        MessagesResponse,
        MessagesResponseData,
        MessagesResponseDataTypedDict,
        MessagesResponseInfo,
        MessagesResponseInfoTypedDict,
        MessagesResponseTypedDict,
    )
    from .outputdata import OutputData, OutputDataTypedDict
    from .outputresponse import OutputResponse, OutputResponseTypedDict
    from .plant import Plant, PlantTypedDict
    from .plantflowdata import PlantFlowData, PlantFlowDataTypedDict, Pv, PvTypedDict
    from .plantflowresponse import PlantFlowResponse, PlantFlowResponseTypedDict
    from .plantinverterinfo import PlantInverterInfo, PlantInverterInfoTypedDict
    from .plantinvertersdata import PlantInvertersData, PlantInvertersDataTypedDict
    from .plantinvertersresponse import (
        PlantInvertersResponse,
        PlantInvertersResponseTypedDict,
    )
    from .plantsresponse import (
        PlantsResponse,
        PlantsResponseData,
        PlantsResponseDataTypedDict,
        PlantsResponseTypedDict,
    )
    from .plantsummary import PlantSummary, PlantSummaryTypedDict
    from .pviv import PvIv, PvIvTypedDict
    from .readinvertersettingsop import (
        ReadInverterSettingsRequest,
        ReadInverterSettingsRequestTypedDict,
    )
    from .realtimevip import RealtimeVip, RealtimeVipTypedDict
    from .security import Security, SecurityTypedDict
    from .tokenrequest import ClientID, GrantType, TokenRequest, TokenRequestTypedDict
    from .tokenresponse import (
        TokenResponse,
        TokenResponseData,
        TokenResponseDataTypedDict,
        TokenResponseTypedDict,
    )
    from .vip import Vip, VipTypedDict
    from .writeinvertersettingsop import (
        WriteInverterSettingsRequest,
        WriteInverterSettingsRequestBody,
        WriteInverterSettingsRequestBodyTypedDict,
        WriteInverterSettingsRequestTypedDict,
        WriteInverterSettingsResponse,
        WriteInverterSettingsResponseTypedDict,
    )

__all__ = [
    "BatteryData",
    "BatteryDataTypedDict",
    "BatteryResponse",
    "BatteryResponseTypedDict",
    "ClientID",
    "DailyOutputResponse",
    "DailyOutputResponseData",
    "DailyOutputResponseDataTypedDict",
    "DailyOutputResponseInfo",
    "DailyOutputResponseInfoTypedDict",
    "DailyOutputResponseTypedDict",
    "EventsResponse",
    "EventsResponseData",
    "EventsResponseDataTypedDict",
    "EventsResponseTypedDict",
    "GatewayExtendedInfo",
    "GatewayExtendedInfoTypedDict",
    "GatewayInfo",
    "GatewayInfoTypedDict",
    "GatewaysResponse",
    "GatewaysResponseData",
    "GatewaysResponseDataTypedDict",
    "GatewaysResponseTypedDict",
    "GenRealtimeData",
    "GenRealtimeDataTypedDict",
    "GenRealtimeResponse",
    "GenRealtimeResponseTypedDict",
    "GetAPIV1InvertersRequest",
    "GetAPIV1InvertersRequestTypedDict",
    "GetBatteryRealtimeRequest",
    "GetBatteryRealtimeRequestTypedDict",
    "GetBearerTokenData",
    "GetBearerTokenDataTypedDict",
    "GetBearerTokenRequest",
    "GetBearerTokenRequestTypedDict",
    "GetBearerTokenResponse",
    "GetBearerTokenResponseTypedDict",
    "GetEventsRequest",
    "GetEventsRequestTypedDict",
    "GetGatewaysRequest",
    "GetGatewaysRequestTypedDict",
    "GetGenRealtimeRequest",
    "GetGenRealtimeRequestTypedDict",
    "GetGridRealtimeRequest",
    "GetGridRealtimeRequestTypedDict",
    "GetInverterDailyOutputRequest",
    "GetInverterDailyOutputRequestTypedDict",
    "GetInverterInputRequest",
    "GetInverterInputRequestTypedDict",
    "GetInverterOutputRequest",
    "GetInverterOutputRequestTypedDict",
    "GetLoadRealtimeRequest",
    "GetLoadRealtimeRequestTypedDict",
    "GetMessagesRequest",
    "GetMessagesRequestTypedDict",
    "GetPlantFlowRequest",
    "GetPlantFlowRequestTypedDict",
    "GetPlantInvertersRequest",
    "GetPlantInvertersRequestTypedDict",
    "GetPlantsRequest",
    "GetPlantsRequestTypedDict",
    "GetPublicKeyRequest",
    "GetPublicKeyRequestTypedDict",
    "GetPublicKeyResponse",
    "GetPublicKeyResponseTypedDict",
    "GrantType",
    "GridData",
    "GridDataTypedDict",
    "GridResponse",
    "GridResponseTypedDict",
    "InputData",
    "InputDataTypedDict",
    "InputResponse",
    "InputResponseTypedDict",
    "Inverter",
    "InverterSettings",
    "InverterSettingsResponse",
    "InverterSettingsResponseTypedDict",
    "InverterSettingsTypedDict",
    "InverterTypedDict",
    "InverterVersion",
    "InverterVersionTypedDict",
    "InvertersResponse",
    "InvertersResponseData",
    "InvertersResponseDataTypedDict",
    "InvertersResponseTypedDict",
    "LoadRealtimeData",
    "LoadRealtimeDataTypedDict",
    "LoadRealtimeResponse",
    "LoadRealtimeResponseTypedDict",
    "MessagesResponse",
    "MessagesResponseData",
    "MessagesResponseDataTypedDict",
    "MessagesResponseInfo",
    "MessagesResponseInfoTypedDict",
    "MessagesResponseTypedDict",
    "OutputData",
    "OutputDataTypedDict",
    "OutputResponse",
    "OutputResponseTypedDict",
    "Plant",
    "PlantFlowData",
    "PlantFlowDataTypedDict",
    "PlantFlowResponse",
    "PlantFlowResponseTypedDict",
    "PlantInverterInfo",
    "PlantInverterInfoTypedDict",
    "PlantInvertersData",
    "PlantInvertersDataTypedDict",
    "PlantInvertersResponse",
    "PlantInvertersResponseTypedDict",
    "PlantSummary",
    "PlantSummaryTypedDict",
    "PlantTypedDict",
    "PlantsResponse",
    "PlantsResponseData",
    "PlantsResponseDataTypedDict",
    "PlantsResponseTypedDict",
    "Pv",
    "PvIv",
    "PvIvTypedDict",
    "PvTypedDict",
    "ReadInverterSettingsRequest",
    "ReadInverterSettingsRequestTypedDict",
    "RealtimeVip",
    "RealtimeVipTypedDict",
    "Record",
    "RecordTypedDict",
    "Security",
    "SecurityTypedDict",
    "TokenRequest",
    "TokenRequestTypedDict",
    "TokenResponse",
    "TokenResponseData",
    "TokenResponseDataTypedDict",
    "TokenResponseTypedDict",
    "Vip",
    "VipTypedDict",
    "WriteInverterSettingsRequest",
    "WriteInverterSettingsRequestBody",
    "WriteInverterSettingsRequestBodyTypedDict",
    "WriteInverterSettingsRequestTypedDict",
    "WriteInverterSettingsResponse",
    "WriteInverterSettingsResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "BatteryData": ".batterydata",
    "BatteryDataTypedDict": ".batterydata",
    "BatteryResponse": ".batteryresponse",
    "BatteryResponseTypedDict": ".batteryresponse",
    "DailyOutputResponse": ".dailyoutputresponse",
    "DailyOutputResponseData": ".dailyoutputresponse",
    "DailyOutputResponseDataTypedDict": ".dailyoutputresponse",
    "DailyOutputResponseInfo": ".dailyoutputresponse",
    "DailyOutputResponseInfoTypedDict": ".dailyoutputresponse",
    "DailyOutputResponseTypedDict": ".dailyoutputresponse",
    "EventsResponse": ".eventsresponse",
    "EventsResponseData": ".eventsresponse",
    "EventsResponseDataTypedDict": ".eventsresponse",
    "EventsResponseTypedDict": ".eventsresponse",
    "Record": ".eventsresponse",
    "RecordTypedDict": ".eventsresponse",
    "GatewayExtendedInfo": ".gatewayextendedinfo",
    "GatewayExtendedInfoTypedDict": ".gatewayextendedinfo",
    "GatewayInfo": ".gatewayinfo",
    "GatewayInfoTypedDict": ".gatewayinfo",
    "GatewaysResponse": ".gatewaysresponse",
    "GatewaysResponseData": ".gatewaysresponse",
    "GatewaysResponseDataTypedDict": ".gatewaysresponse",
    "GatewaysResponseTypedDict": ".gatewaysresponse",
    "GenRealtimeData": ".genrealtimedata",
    "GenRealtimeDataTypedDict": ".genrealtimedata",
    "GenRealtimeResponse": ".genrealtimeresponse",
    "GenRealtimeResponseTypedDict": ".genrealtimeresponse",
    "GetAPIV1InvertersRequest": ".get_api_v1_invertersop",
    "GetAPIV1InvertersRequestTypedDict": ".get_api_v1_invertersop",
    "GetBatteryRealtimeRequest": ".getbatteryrealtimeop",
    "GetBatteryRealtimeRequestTypedDict": ".getbatteryrealtimeop",
    "GetBearerTokenData": ".getbearertokenop",
    "GetBearerTokenDataTypedDict": ".getbearertokenop",
    "GetBearerTokenRequest": ".getbearertokenop",
    "GetBearerTokenRequestTypedDict": ".getbearertokenop",
    "GetBearerTokenResponse": ".getbearertokenop",
    "GetBearerTokenResponseTypedDict": ".getbearertokenop",
    "GetEventsRequest": ".geteventsop",
    "GetEventsRequestTypedDict": ".geteventsop",
    "GetGatewaysRequest": ".getgatewaysop",
    "GetGatewaysRequestTypedDict": ".getgatewaysop",
    "GetGenRealtimeRequest": ".getgenrealtimeop",
    "GetGenRealtimeRequestTypedDict": ".getgenrealtimeop",
    "GetGridRealtimeRequest": ".getgridrealtimeop",
    "GetGridRealtimeRequestTypedDict": ".getgridrealtimeop",
    "GetInverterDailyOutputRequest": ".getinverterdailyoutputop",
    "GetInverterDailyOutputRequestTypedDict": ".getinverterdailyoutputop",
    "GetInverterInputRequest": ".getinverterinputop",
    "GetInverterInputRequestTypedDict": ".getinverterinputop",
    "GetInverterOutputRequest": ".getinverteroutputop",
    "GetInverterOutputRequestTypedDict": ".getinverteroutputop",
    "GetLoadRealtimeRequest": ".getloadrealtimeop",
    "GetLoadRealtimeRequestTypedDict": ".getloadrealtimeop",
    "GetMessagesRequest": ".getmessagesop",
    "GetMessagesRequestTypedDict": ".getmessagesop",
    "GetPlantFlowRequest": ".getplantflowop",
    "GetPlantFlowRequestTypedDict": ".getplantflowop",
    "GetPlantInvertersRequest": ".getplantinvertersop",
    "GetPlantInvertersRequestTypedDict": ".getplantinvertersop",
    "GetPlantsRequest": ".getplantsop",
    "GetPlantsRequestTypedDict": ".getplantsop",
    "GetPublicKeyRequest": ".getpublickeyop",
    "GetPublicKeyRequestTypedDict": ".getpublickeyop",
    "GetPublicKeyResponse": ".getpublickeyop",
    "GetPublicKeyResponseTypedDict": ".getpublickeyop",
    "GridData": ".griddata",
    "GridDataTypedDict": ".griddata",
    "GridResponse": ".gridresponse",
    "GridResponseTypedDict": ".gridresponse",
    "InputData": ".inputdata",
    "InputDataTypedDict": ".inputdata",
    "InputResponse": ".inputresponse",
    "InputResponseTypedDict": ".inputresponse",
    "Inverter": ".inverter",
    "InverterTypedDict": ".inverter",
    "InverterSettings": ".invertersettings",
    "InverterSettingsTypedDict": ".invertersettings",
    "InverterSettingsResponse": ".invertersettingsresponse",
    "InverterSettingsResponseTypedDict": ".invertersettingsresponse",
    "InvertersResponse": ".invertersresponse",
    "InvertersResponseData": ".invertersresponse",
    "InvertersResponseDataTypedDict": ".invertersresponse",
    "InvertersResponseTypedDict": ".invertersresponse",
    "InverterVersion": ".inverterversion",
    "InverterVersionTypedDict": ".inverterversion",
    "LoadRealtimeData": ".loadrealtimedata",
    "LoadRealtimeDataTypedDict": ".loadrealtimedata",
    "LoadRealtimeResponse": ".loadrealtimeresponse",
    "LoadRealtimeResponseTypedDict": ".loadrealtimeresponse",
    "MessagesResponse": ".messagesresponse",
    "MessagesResponseData": ".messagesresponse",
    "MessagesResponseDataTypedDict": ".messagesresponse",
    "MessagesResponseInfo": ".messagesresponse",
    "MessagesResponseInfoTypedDict": ".messagesresponse",
    "MessagesResponseTypedDict": ".messagesresponse",
    "OutputData": ".outputdata",
    "OutputDataTypedDict": ".outputdata",
    "OutputResponse": ".outputresponse",
    "OutputResponseTypedDict": ".outputresponse",
    "Plant": ".plant",
    "PlantTypedDict": ".plant",
    "PlantFlowData": ".plantflowdata",
    "PlantFlowDataTypedDict": ".plantflowdata",
    "Pv": ".plantflowdata",
    "PvTypedDict": ".plantflowdata",
    "PlantFlowResponse": ".plantflowresponse",
    "PlantFlowResponseTypedDict": ".plantflowresponse",
    "PlantInverterInfo": ".plantinverterinfo",
    "PlantInverterInfoTypedDict": ".plantinverterinfo",
    "PlantInvertersData": ".plantinvertersdata",
    "PlantInvertersDataTypedDict": ".plantinvertersdata",
    "PlantInvertersResponse": ".plantinvertersresponse",
    "PlantInvertersResponseTypedDict": ".plantinvertersresponse",
    "PlantsResponse": ".plantsresponse",
    "PlantsResponseData": ".plantsresponse",
    "PlantsResponseDataTypedDict": ".plantsresponse",
    "PlantsResponseTypedDict": ".plantsresponse",
    "PlantSummary": ".plantsummary",
    "PlantSummaryTypedDict": ".plantsummary",
    "PvIv": ".pviv",
    "PvIvTypedDict": ".pviv",
    "ReadInverterSettingsRequest": ".readinvertersettingsop",
    "ReadInverterSettingsRequestTypedDict": ".readinvertersettingsop",
    "RealtimeVip": ".realtimevip",
    "RealtimeVipTypedDict": ".realtimevip",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "ClientID": ".tokenrequest",
    "GrantType": ".tokenrequest",
    "TokenRequest": ".tokenrequest",
    "TokenRequestTypedDict": ".tokenrequest",
    "TokenResponse": ".tokenresponse",
    "TokenResponseData": ".tokenresponse",
    "TokenResponseDataTypedDict": ".tokenresponse",
    "TokenResponseTypedDict": ".tokenresponse",
    "Vip": ".vip",
    "VipTypedDict": ".vip",
    "WriteInverterSettingsRequest": ".writeinvertersettingsop",
    "WriteInverterSettingsRequestBody": ".writeinvertersettingsop",
    "WriteInverterSettingsRequestBodyTypedDict": ".writeinvertersettingsop",
    "WriteInverterSettingsRequestTypedDict": ".writeinvertersettingsop",
    "WriteInverterSettingsResponse": ".writeinvertersettingsop",
    "WriteInverterSettingsResponseTypedDict": ".writeinvertersettingsop",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
