"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BatteryDataTypedDict(TypedDict):
    etoday_chg: NotRequired[float]
    r"""Battery charge energy today (kWh)"""
    etoday_dischg: NotRequired[float]
    r"""Battery discharge energy today (kWh)"""
    emonth_chg: NotRequired[float]
    r"""Battery charge energy this month (kWh)"""
    emonth_dischg: NotRequired[float]
    r"""Battery discharge energy this month (kWh)"""
    eyear_chg: NotRequired[float]
    r"""Battery charge energy this year (kWh)"""
    eyear_dischg: NotRequired[float]
    r"""Battery discharge energy this year (kWh)"""
    etotal_chg: NotRequired[float]
    r"""Total battery charge energy (kWh)"""
    etotal_dischg: NotRequired[float]
    r"""Total battery discharge energy (kWh)"""
    type: NotRequired[str]
    r"""Battery type"""
    power: NotRequired[float]
    r"""Battery power (kW)"""
    capacity: NotRequired[float]
    r"""Battery capacity (kWh)"""
    correct_cap: NotRequired[float]
    r"""Corrected capacity (kWh)"""
    current: NotRequired[float]
    r"""Battery current (A)"""
    voltage: NotRequired[float]
    r"""Battery voltage (V)"""
    temp: NotRequired[float]
    r"""Battery temperature (°C)"""
    soc: NotRequired[float]
    r"""State of charge (%)"""
    charge_volt: NotRequired[float]
    r"""Charge voltage (V)"""
    discharge_volt: NotRequired[float]
    r"""Discharge voltage (V)"""
    charge_current_limit: NotRequired[float]
    r"""Charge current limit (A)"""
    discharge_current_limit: NotRequired[float]
    r"""Discharge current limit (A)"""
    max_charge_current_limit: NotRequired[float]
    r"""Maximum charge current limit (A)"""
    max_discharge_current_limit: NotRequired[float]
    r"""Maximum discharge current limit (A)"""
    status: NotRequired[str]
    r"""Battery status"""
    battery_soc1: NotRequired[float]
    r"""Battery 1 state of charge (%)"""
    battery_current1: NotRequired[float]
    r"""Battery 1 current (A)"""
    battery_volt1: NotRequired[float]
    r"""Battery 1 voltage (V)"""
    battery_power1: NotRequired[float]
    r"""Battery 1 power (kW)"""
    battery_temp1: NotRequired[float]
    r"""Battery 1 temperature (°C)"""
    battery_status2: NotRequired[str]
    r"""Battery 2 status"""
    battery_soc2: NotRequired[float]
    r"""Battery 2 state of charge (%)"""
    battery_current2: NotRequired[float]
    r"""Battery 2 current (A)"""
    battery_volt2: NotRequired[float]
    r"""Battery 2 voltage (V)"""
    battery_power2: NotRequired[float]
    r"""Battery 2 power (kW)"""
    battery_temp2: NotRequired[float]
    r"""Battery 2 temperature (°C)"""
    number_of_batteries: NotRequired[int]
    r"""Number of batteries"""
    batt1_factory: NotRequired[str]
    r"""Battery 1 factory"""
    batt2_factory: NotRequired[str]
    r"""Battery 2 factory"""


class BatteryData(BaseModel):
    etoday_chg: Annotated[Optional[float], pydantic.Field(alias="etodayChg")] = None
    r"""Battery charge energy today (kWh)"""

    etoday_dischg: Annotated[Optional[float], pydantic.Field(alias="etodayDischg")] = (
        None
    )
    r"""Battery discharge energy today (kWh)"""

    emonth_chg: Annotated[Optional[float], pydantic.Field(alias="emonthChg")] = None
    r"""Battery charge energy this month (kWh)"""

    emonth_dischg: Annotated[Optional[float], pydantic.Field(alias="emonthDischg")] = (
        None
    )
    r"""Battery discharge energy this month (kWh)"""

    eyear_chg: Annotated[Optional[float], pydantic.Field(alias="eyearChg")] = None
    r"""Battery charge energy this year (kWh)"""

    eyear_dischg: Annotated[Optional[float], pydantic.Field(alias="eyearDischg")] = None
    r"""Battery discharge energy this year (kWh)"""

    etotal_chg: Annotated[Optional[float], pydantic.Field(alias="etotalChg")] = None
    r"""Total battery charge energy (kWh)"""

    etotal_dischg: Annotated[Optional[float], pydantic.Field(alias="etotalDischg")] = (
        None
    )
    r"""Total battery discharge energy (kWh)"""

    type: Optional[str] = None
    r"""Battery type"""

    power: Optional[float] = None
    r"""Battery power (kW)"""

    capacity: Optional[float] = None
    r"""Battery capacity (kWh)"""

    correct_cap: Annotated[Optional[float], pydantic.Field(alias="correctCap")] = None
    r"""Corrected capacity (kWh)"""

    current: Optional[float] = None
    r"""Battery current (A)"""

    voltage: Optional[float] = None
    r"""Battery voltage (V)"""

    temp: Optional[float] = None
    r"""Battery temperature (°C)"""

    soc: Optional[float] = None
    r"""State of charge (%)"""

    charge_volt: Annotated[Optional[float], pydantic.Field(alias="chargeVolt")] = None
    r"""Charge voltage (V)"""

    discharge_volt: Annotated[
        Optional[float], pydantic.Field(alias="dischargeVolt")
    ] = None
    r"""Discharge voltage (V)"""

    charge_current_limit: Annotated[
        Optional[float], pydantic.Field(alias="chargeCurrentLimit")
    ] = None
    r"""Charge current limit (A)"""

    discharge_current_limit: Annotated[
        Optional[float], pydantic.Field(alias="dischargeCurrentLimit")
    ] = None
    r"""Discharge current limit (A)"""

    max_charge_current_limit: Annotated[
        Optional[float], pydantic.Field(alias="maxChargeCurrentLimit")
    ] = None
    r"""Maximum charge current limit (A)"""

    max_discharge_current_limit: Annotated[
        Optional[float], pydantic.Field(alias="maxDischargeCurrentLimit")
    ] = None
    r"""Maximum discharge current limit (A)"""

    status: Optional[str] = None
    r"""Battery status"""

    battery_soc1: Annotated[Optional[float], pydantic.Field(alias="batterySoc1")] = None
    r"""Battery 1 state of charge (%)"""

    battery_current1: Annotated[
        Optional[float], pydantic.Field(alias="batteryCurrent1")
    ] = None
    r"""Battery 1 current (A)"""

    battery_volt1: Annotated[Optional[float], pydantic.Field(alias="batteryVolt1")] = (
        None
    )
    r"""Battery 1 voltage (V)"""

    battery_power1: Annotated[
        Optional[float], pydantic.Field(alias="batteryPower1")
    ] = None
    r"""Battery 1 power (kW)"""

    battery_temp1: Annotated[Optional[float], pydantic.Field(alias="batteryTemp1")] = (
        None
    )
    r"""Battery 1 temperature (°C)"""

    battery_status2: Annotated[
        Optional[str], pydantic.Field(alias="batteryStatus2")
    ] = None
    r"""Battery 2 status"""

    battery_soc2: Annotated[Optional[float], pydantic.Field(alias="batterySoc2")] = None
    r"""Battery 2 state of charge (%)"""

    battery_current2: Annotated[
        Optional[float], pydantic.Field(alias="batteryCurrent2")
    ] = None
    r"""Battery 2 current (A)"""

    battery_volt2: Annotated[Optional[float], pydantic.Field(alias="batteryVolt2")] = (
        None
    )
    r"""Battery 2 voltage (V)"""

    battery_power2: Annotated[
        Optional[float], pydantic.Field(alias="batteryPower2")
    ] = None
    r"""Battery 2 power (kW)"""

    battery_temp2: Annotated[Optional[float], pydantic.Field(alias="batteryTemp2")] = (
        None
    )
    r"""Battery 2 temperature (°C)"""

    number_of_batteries: Annotated[
        Optional[int], pydantic.Field(alias="numberOfBatteries")
    ] = None
    r"""Number of batteries"""

    batt1_factory: Annotated[Optional[str], pydantic.Field(alias="batt1Factory")] = None
    r"""Battery 1 factory"""

    batt2_factory: Annotated[Optional[str], pydantic.Field(alias="batt2Factory")] = None
    r"""Battery 2 factory"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "etodayChg",
                "etodayDischg",
                "emonthChg",
                "emonthDischg",
                "eyearChg",
                "eyearDischg",
                "etotalChg",
                "etotalDischg",
                "type",
                "power",
                "capacity",
                "correctCap",
                "current",
                "voltage",
                "temp",
                "soc",
                "chargeVolt",
                "dischargeVolt",
                "chargeCurrentLimit",
                "dischargeCurrentLimit",
                "maxChargeCurrentLimit",
                "maxDischargeCurrentLimit",
                "status",
                "batterySoc1",
                "batteryCurrent1",
                "batteryVolt1",
                "batteryPower1",
                "batteryTemp1",
                "batteryStatus2",
                "batterySoc2",
                "batteryCurrent2",
                "batteryVolt2",
                "batteryPower2",
                "batteryTemp2",
                "numberOfBatteries",
                "batt1Factory",
                "batt2Factory",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    BatteryData.model_rebuild()
except NameError:
    pass
