"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RecordTypedDict(TypedDict):
    pass


class Record(BaseModel):
    pass


class EventsResponseDataTypedDict(TypedDict):
    next_token: NotRequired[Nullable[str]]
    record: NotRequired[List[RecordTypedDict]]


class EventsResponseData(BaseModel):
    next_token: Annotated[OptionalNullable[str], pydantic.Field(alias="nextToken")] = (
        UNSET
    )

    record: Optional[List[Record]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["nextToken", "record"])
        nullable_fields = set(["nextToken"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class EventsResponseTypedDict(TypedDict):
    success: NotRequired[bool]
    code: NotRequired[int]
    msg: NotRequired[str]
    data: NotRequired[EventsResponseDataTypedDict]


class EventsResponse(BaseModel):
    success: Optional[bool] = None

    code: Optional[int] = None

    msg: Optional[str] = None

    data: Optional[EventsResponseData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "code", "msg", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    EventsResponseData.model_rebuild()
except NameError:
    pass
