"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GatewayExtendedInfoTypedDict(TypedDict):
    id: NotRequired[int]
    sn: NotRequired[str]
    key: NotRequired[str]
    status: NotRequired[int]
    comm_type: NotRequired[int]
    signal: NotRequired[int]
    soft_ver: NotRequired[str]
    hard_ver: NotRequired[str]
    update_at: NotRequired[datetime]
    protocol_type: NotRequired[int]
    model: NotRequired[str]
    lldt: NotRequired[datetime]
    upload_cycle: NotRequired[int]
    dev_name: NotRequired[str]
    comm_type_name: NotRequired[str]
    proto: NotRequired[str]


class GatewayExtendedInfo(BaseModel):
    id: Optional[int] = None

    sn: Optional[str] = None

    key: Optional[str] = None

    status: Optional[int] = None

    comm_type: Annotated[Optional[int], pydantic.Field(alias="commType")] = None

    signal: Optional[int] = None

    soft_ver: Annotated[Optional[str], pydantic.Field(alias="softVer")] = None

    hard_ver: Annotated[Optional[str], pydantic.Field(alias="hardVer")] = None

    update_at: Annotated[Optional[datetime], pydantic.Field(alias="updateAt")] = None

    protocol_type: Annotated[Optional[int], pydantic.Field(alias="protocolType")] = None

    model: Optional[str] = None

    lldt: Optional[datetime] = None

    upload_cycle: Annotated[Optional[int], pydantic.Field(alias="uploadCycle")] = None

    dev_name: Annotated[Optional[str], pydantic.Field(alias="devName")] = None

    comm_type_name: Annotated[Optional[str], pydantic.Field(alias="commTypeName")] = (
        None
    )

    proto: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "sn",
                "key",
                "status",
                "commType",
                "signal",
                "softVer",
                "hardVer",
                "updateAt",
                "protocolType",
                "model",
                "lldt",
                "uploadCycle",
                "devName",
                "commTypeName",
                "proto",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GatewayExtendedInfo.model_rebuild()
except NameError:
    pass
