"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .realtimevip import RealtimeVip, RealtimeVipTypedDict
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GenRealtimeDataTypedDict(TypedDict):
    gen_total: NotRequired[float]
    gen_daily: NotRequired[float]
    total_power: NotRequired[float]
    gen_fac: NotRequired[float]
    vip: NotRequired[List[RealtimeVipTypedDict]]


class GenRealtimeData(BaseModel):
    gen_total: Annotated[Optional[float], pydantic.Field(alias="genTotal")] = None

    gen_daily: Annotated[Optional[float], pydantic.Field(alias="genDaily")] = None

    total_power: Annotated[Optional[float], pydantic.Field(alias="totalPower")] = None

    gen_fac: Annotated[Optional[float], pydantic.Field(alias="genFac")] = None

    vip: Optional[List[RealtimeVip]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["genTotal", "genDaily", "totalPower", "genFac", "vip"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GenRealtimeData.model_rebuild()
except NameError:
    pass
