"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from sunsynk_api_client.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetAPIV1InvertersRequestTypedDict(TypedDict):
    page: NotRequired[int]
    limit: NotRequired[int]
    total: NotRequired[int]
    status: NotRequired[int]
    sn: NotRequired[str]
    plant_id: NotRequired[str]
    type: NotRequired[int]
    soft_ver: NotRequired[str]
    hmi_ver: NotRequired[str]
    agent_company_id: NotRequired[int]
    gsn: NotRequired[str]


class GetAPIV1InvertersRequest(BaseModel):
    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10

    total: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0

    status: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = -1

    sn: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ""

    plant_id: Annotated[
        Optional[str],
        pydantic.Field(alias="plantId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ""

    type: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = -2

    soft_ver: Annotated[
        Optional[str],
        pydantic.Field(alias="softVer"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ""

    hmi_ver: Annotated[
        Optional[str],
        pydantic.Field(alias="hmiVer"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ""

    agent_company_id: Annotated[
        Optional[int],
        pydantic.Field(alias="agentCompanyId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = -1

    gsn: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "page",
                "limit",
                "total",
                "status",
                "sn",
                "plantId",
                "type",
                "softVer",
                "hmiVer",
                "agentCompanyId",
                "gsn",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
