"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetBearerTokenRequestTypedDict(TypedDict):
    password: str
    r"""RSA encrypted password (Base64 encoded)"""
    username: str
    r"""User's username"""
    area_code: NotRequired[str]
    client_id: NotRequired[str]
    grant_type: NotRequired[str]
    source: NotRequired[str]
    nonce: NotRequired[int]
    r"""Unix timestamp for request"""
    sign: NotRequired[str]
    r"""MD5 hash of nonce + source + public key snippet"""


class GetBearerTokenRequest(BaseModel):
    password: str
    r"""RSA encrypted password (Base64 encoded)"""

    username: str
    r"""User's username"""

    area_code: Annotated[Optional[str], pydantic.Field(alias="areaCode")] = "sunsynk"

    client_id: Optional[str] = "csp-web"

    grant_type: Optional[str] = "password"

    source: Optional[str] = "sunsynk"

    nonce: Optional[int] = None
    r"""Unix timestamp for request"""

    sign: Optional[str] = None
    r"""MD5 hash of nonce + source + public key snippet"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["areaCode", "client_id", "grant_type", "source", "nonce", "sign"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetBearerTokenDataTypedDict(TypedDict):
    access_token: NotRequired[str]
    expires_in: NotRequired[int]
    token_type: NotRequired[str]


class GetBearerTokenData(BaseModel):
    access_token: Optional[str] = None

    expires_in: Optional[int] = None

    token_type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["access_token", "expires_in", "token_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetBearerTokenResponseTypedDict(TypedDict):
    r"""Successful authentication"""

    msg: NotRequired[str]
    code: NotRequired[int]
    data: NotRequired[GetBearerTokenDataTypedDict]


class GetBearerTokenResponse(BaseModel):
    r"""Successful authentication"""

    msg: Optional[str] = None

    code: Optional[int] = None

    data: Optional[GetBearerTokenData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["msg", "code", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GetBearerTokenRequest.model_rebuild()
except NameError:
    pass
