"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 64f3c2ffb96e

from __future__ import annotations
from sunsynk_api_client.types import BaseModel
from sunsynk_api_client.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from typing_extensions import Annotated, TypedDict


class GetBatteryRealtimeRequestTypedDict(TypedDict):
    sn: str
    lan: int


class GetBatteryRealtimeRequest(BaseModel):
    sn: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    lan: Annotated[
        int, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = -1
