"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from sunsynk_api_client.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetEventsRequestTypedDict(TypedDict):
    type: int
    page: NotRequired[int]
    limit: NotRequired[int]
    lan: NotRequired[str]
    sdate: NotRequired[date]
    edate: NotRequired[date]


class GetEventsRequest(BaseModel):
    type: Annotated[
        int, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50

    lan: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "en"

    sdate: Annotated[
        Optional[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    edate: Annotated[
        Optional[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["page", "limit", "lan", "sdate", "edate"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetEventsResponseTypedDict(TypedDict):
    r"""List of events"""


class GetEventsResponse(BaseModel):
    r"""List of events"""
