"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sunsynk_api_client.types import BaseModel
from sunsynk_api_client.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetGenRealtimeRequestTypedDict(TypedDict):
    sn: str


class GetGenRealtimeRequest(BaseModel):
    sn: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
