"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from sunsynk_api_client.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetGatewaysRequestTypedDict(TypedDict):
    page: NotRequired[int]
    limit: NotRequired[int]
    status: NotRequired[str]
    sn: NotRequired[str]
    plant_id: NotRequired[str]
    upload_cycle: NotRequired[str]
    soft_ver: NotRequired[str]
    hard_ver: NotRequired[str]
    inv_sn: NotRequired[str]
    protocol: NotRequired[str]
    agent_company_id: NotRequired[str]
    lan: NotRequired[str]


class GetGatewaysRequest(BaseModel):
    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10

    status: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "-1"

    sn: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    plant_id: Annotated[
        Optional[str],
        pydantic.Field(alias="plantId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    upload_cycle: Annotated[
        Optional[str],
        pydantic.Field(alias="uploadCycle"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "-1"

    soft_ver: Annotated[
        Optional[str],
        pydantic.Field(alias="softVer"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    hard_ver: Annotated[
        Optional[str],
        pydantic.Field(alias="hardVer"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    inv_sn: Annotated[
        Optional[str],
        pydantic.Field(alias="invSn"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    protocol: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "-1"

    agent_company_id: Annotated[
        Optional[str],
        pydantic.Field(alias="agentCompanyId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "-1"

    lan: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "en"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "page",
                "limit",
                "status",
                "sn",
                "plantId",
                "uploadCycle",
                "softVer",
                "hardVer",
                "invSn",
                "protocol",
                "agentCompanyId",
                "lan",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
