"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 438a1232453f

from __future__ import annotations
from datetime import date
import pydantic
from sunsynk_api_client.types import BaseModel
from sunsynk_api_client.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from typing_extensions import Annotated, TypedDict


class GetInverterDailyOutputRequestTypedDict(TypedDict):
    sn: str
    date_: date
    lan: str
    column: str


class GetInverterDailyOutputRequest(BaseModel):
    sn: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    date_: Annotated[
        date,
        pydantic.Field(alias="date"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]

    lan: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "en"

    column: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "dc_temp,igbt_temp"
