"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from sunsynk_api_client.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPublicKeyRequestTypedDict(TypedDict):
    nonce: int
    sign: str
    source: str


class GetPublicKeyRequest(BaseModel):
    nonce: Annotated[
        int, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    sign: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    source: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "sunsynk"


class GetPublicKeyResponseTypedDict(TypedDict):
    r"""Public key retrieved"""

    data: NotRequired[str]
    r"""Base64 encoded RSA public key"""


class GetPublicKeyResponse(BaseModel):
    r"""Public key retrieved"""

    data: Optional[str] = None
    r"""Base64 encoded RSA public key"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
