"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 44978ac8a4b8

from __future__ import annotations
import pydantic
from sunsynk_api_client.types import BaseModel
from sunsynk_api_client.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from typing_extensions import Annotated, TypedDict


class GetPlantInvertersRequestTypedDict(TypedDict):
    plant_id: str
    page: int
    limit: int
    status: str
    type: str


class GetPlantInvertersRequest(BaseModel):
    plant_id: Annotated[
        str,
        pydantic.Field(alias="plantId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    page: Annotated[
        int, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = 1

    limit: Annotated[
        int, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = 1

    status: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "-1"

    type: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "-2"
