"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from sunsynk_api_client.types import BaseModel
from sunsynk_api_client.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetPlantFlowRequestTypedDict(TypedDict):
    plant_id: str


class GetPlantFlowRequest(BaseModel):
    plant_id: Annotated[
        str,
        pydantic.Field(alias="plantId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class GetPlantFlowResponseTypedDict(TypedDict):
    r"""Plant flow data"""


class GetPlantFlowResponse(BaseModel):
    r"""Plant flow data"""
