"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4e9827226627

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from sunsynk_api_client.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPlantRequestTypedDict(TypedDict):
    plant_id: str
    lan: str
    id: NotRequired[str]


class GetPlantRequest(BaseModel):
    plant_id: Annotated[
        str,
        pydantic.Field(alias="plantId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    lan: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "en"

    id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
