"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .vip import Vip, VipTypedDict
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GridDataTypedDict(TypedDict):
    vip: NotRequired[List[VipTypedDict]]
    pac: NotRequired[float]
    r"""Grid power (kW)"""
    qac: NotRequired[float]
    r"""Reactive power (kVar)"""
    fac: NotRequired[float]
    r"""Grid frequency (Hz)"""
    pf: NotRequired[float]
    r"""Power factor"""
    status: NotRequired[str]
    r"""Grid status"""
    etoday_from: NotRequired[float]
    r"""Energy imported today (kWh)"""
    etoday_to: NotRequired[float]
    r"""Energy exported today (kWh)"""
    etotal_from: NotRequired[float]
    r"""Total energy imported (kWh)"""
    etotal_to: NotRequired[float]
    r"""Total energy exported (kWh)"""
    limiter_power_arr: NotRequired[List[float]]
    limiter_total_power: NotRequired[float]
    r"""Total limiter power (kW)"""


class GridData(BaseModel):
    vip: Optional[List[Vip]] = None

    pac: Optional[float] = None
    r"""Grid power (kW)"""

    qac: Optional[float] = None
    r"""Reactive power (kVar)"""

    fac: Optional[float] = None
    r"""Grid frequency (Hz)"""

    pf: Optional[float] = None
    r"""Power factor"""

    status: Optional[str] = None
    r"""Grid status"""

    etoday_from: Annotated[Optional[float], pydantic.Field(alias="etodayFrom")] = None
    r"""Energy imported today (kWh)"""

    etoday_to: Annotated[Optional[float], pydantic.Field(alias="etodayTo")] = None
    r"""Energy exported today (kWh)"""

    etotal_from: Annotated[Optional[float], pydantic.Field(alias="etotalFrom")] = None
    r"""Total energy imported (kWh)"""

    etotal_to: Annotated[Optional[float], pydantic.Field(alias="etotalTo")] = None
    r"""Total energy exported (kWh)"""

    limiter_power_arr: Annotated[
        Optional[List[float]], pydantic.Field(alias="limiterPowerArr")
    ] = None

    limiter_total_power: Annotated[
        Optional[float], pydantic.Field(alias="limiterTotalPower")
    ] = None
    r"""Total limiter power (kW)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "vip",
                "pac",
                "qac",
                "fac",
                "pf",
                "status",
                "etodayFrom",
                "etodayTo",
                "etotalFrom",
                "etotalTo",
                "limiterPowerArr",
                "limiterTotalPower",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GridData.model_rebuild()
except NameError:
    pass
