"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pviv import PvIv, PvIvTypedDict
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InputDataTypedDict(TypedDict):
    etoday: NotRequired[float]
    r"""Energy generated today (kWh)"""
    etotal: NotRequired[float]
    r"""Total energy generated (kWh)"""
    pac: NotRequired[float]
    r"""Current power (kW)"""
    pv_iv: NotRequired[List[PvIvTypedDict]]


class InputData(BaseModel):
    etoday: Optional[float] = None
    r"""Energy generated today (kWh)"""

    etotal: Optional[float] = None
    r"""Total energy generated (kWh)"""

    pac: Optional[float] = None
    r"""Current power (kW)"""

    pv_iv: Annotated[Optional[List[PvIv]], pydantic.Field(alias="pvIV")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["etoday", "etotal", "pac", "pvIV"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    InputData.model_rebuild()
except NameError:
    pass
