"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InverterVersionTypedDict(TypedDict):
    master_ver: NotRequired[str]
    soft_ver: NotRequired[str]
    hard_ver: NotRequired[str]
    hmi_ver: NotRequired[str]
    bms_ver: NotRequired[str]


class InverterVersion(BaseModel):
    master_ver: Annotated[Optional[str], pydantic.Field(alias="masterVer")] = None

    soft_ver: Annotated[Optional[str], pydantic.Field(alias="softVer")] = None

    hard_ver: Annotated[Optional[str], pydantic.Field(alias="hardVer")] = None

    hmi_ver: Annotated[Optional[str], pydantic.Field(alias="hmiVer")] = None

    bms_ver: Annotated[Optional[str], pydantic.Field(alias="bmsVer")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["masterVer", "softVer", "hardVer", "hmiVer", "bmsVer"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    InverterVersion.model_rebuild()
except NameError:
    pass
