"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gatewayinfo import GatewayInfo, GatewayInfoTypedDict
from .inverterversion import InverterVersion, InverterVersionTypedDict
from .plantsummary import PlantSummary, PlantSummaryTypedDict
from datetime import datetime
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InverterTypedDict(TypedDict):
    sn: NotRequired[str]
    r"""Serial number"""
    alias: NotRequired[str]
    r"""Inverter alias"""
    gsn: NotRequired[str]
    r"""Gateway serial number"""
    status: NotRequired[str]
    r"""Inverter status"""
    type: NotRequired[str]
    r"""Inverter type"""
    comm_type_name: NotRequired[str]
    r"""Communication type name"""
    cust_code: NotRequired[str]
    r"""Customer code"""
    version: NotRequired[InverterVersionTypedDict]
    model: NotRequired[str]
    r"""Inverter model"""
    equip_mode: NotRequired[int]
    r"""Equipment mode"""
    pac: NotRequired[float]
    r"""Current power (AC)"""
    etoday: NotRequired[float]
    r"""Energy generated today"""
    etotal: NotRequired[float]
    r"""Total energy generated"""
    update_at: NotRequired[datetime]
    r"""Last update timestamp"""
    opened: NotRequired[bool]
    r"""Whether inverter is opened"""
    plant: NotRequired[PlantSummaryTypedDict]
    gateway: NotRequired[GatewayInfoTypedDict]
    sunsynk_equip: NotRequired[str]
    protocol_identifier: NotRequired[str]


class Inverter(BaseModel):
    sn: Optional[str] = None
    r"""Serial number"""

    alias: Optional[str] = None
    r"""Inverter alias"""

    gsn: Optional[str] = None
    r"""Gateway serial number"""

    status: Optional[str] = None
    r"""Inverter status"""

    type: Optional[str] = None
    r"""Inverter type"""

    comm_type_name: Annotated[Optional[str], pydantic.Field(alias="commTypeName")] = (
        None
    )
    r"""Communication type name"""

    cust_code: Annotated[Optional[str], pydantic.Field(alias="custCode")] = None
    r"""Customer code"""

    version: Optional[InverterVersion] = None

    model: Optional[str] = None
    r"""Inverter model"""

    equip_mode: Annotated[Optional[int], pydantic.Field(alias="equipMode")] = None
    r"""Equipment mode"""

    pac: Optional[float] = None
    r"""Current power (AC)"""

    etoday: Optional[float] = None
    r"""Energy generated today"""

    etotal: Optional[float] = None
    r"""Total energy generated"""

    update_at: Annotated[Optional[datetime], pydantic.Field(alias="updateAt")] = None
    r"""Last update timestamp"""

    opened: Optional[bool] = None
    r"""Whether inverter is opened"""

    plant: Optional[PlantSummary] = None

    gateway: Optional[GatewayInfo] = None

    sunsynk_equip: Annotated[Optional[str], pydantic.Field(alias="sunsynkEquip")] = None

    protocol_identifier: Annotated[
        Optional[str], pydantic.Field(alias="protocolIdentifier")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "sn",
                "alias",
                "gsn",
                "status",
                "type",
                "commTypeName",
                "custCode",
                "version",
                "model",
                "equipMode",
                "pac",
                "etoday",
                "etotal",
                "updateAt",
                "opened",
                "plant",
                "gateway",
                "sunsynkEquip",
                "protocolIdentifier",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Inverter.model_rebuild()
except NameError:
    pass
