"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .inverter import Inverter, InverterTypedDict
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class InvertersResponseDataTypedDict(TypedDict):
    total: NotRequired[int]
    infos: NotRequired[List[InverterTypedDict]]


class InvertersResponseData(BaseModel):
    total: Optional[int] = None

    infos: Optional[List[Inverter]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["total", "infos"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class InvertersResponseTypedDict(TypedDict):
    success: NotRequired[bool]
    data: NotRequired[InvertersResponseDataTypedDict]


class InvertersResponse(BaseModel):
    success: Optional[bool] = None

    data: Optional[InvertersResponseData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
