"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: f1e8c68ff1a9

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InverterSettingsSetTypedDict(TypedDict):
    r"""Inverter settings to update. All properties are optional — only included fields will be updated. This endpoint accepts partial requests."""

    sn: NotRequired[str]
    r"""Inverter serial number"""
    safety_type: NotRequired[str]
    batt_mode: NotRequired[str]
    solar_sell: NotRequired[str]
    pv_max_limit: NotRequired[str]
    energy_mode: NotRequired[str]
    peak_and_vallery: NotRequired[str]
    sys_work_mode: NotRequired[str]
    sell_time1: NotRequired[str]
    r"""Time slot 1 start time (HH:MM)"""
    sell_time2: NotRequired[str]
    r"""Time slot 2 start time (HH:MM)"""
    sell_time3: NotRequired[str]
    r"""Time slot 3 start time (HH:MM)"""
    sell_time4: NotRequired[str]
    r"""Time slot 4 start time (HH:MM)"""
    sell_time5: NotRequired[str]
    r"""Time slot 5 start time (HH:MM)"""
    sell_time6: NotRequired[str]
    r"""Time slot 6 start time (HH:MM)"""
    sell_time1_pac: NotRequired[str]
    sell_time2_pac: NotRequired[str]
    sell_time3_pac: NotRequired[str]
    sell_time4_pac: NotRequired[str]
    sell_time5_pac: NotRequired[str]
    sell_time6_pac: NotRequired[str]
    cap1: NotRequired[str]
    r"""Battery capacity threshold for time slot 1 (%)"""
    cap2: NotRequired[str]
    r"""Battery capacity threshold for time slot 2 (%)"""
    cap3: NotRequired[str]
    r"""Battery capacity threshold for time slot 3 (%)"""
    cap4: NotRequired[str]
    r"""Battery capacity threshold for time slot 4 (%)"""
    cap5: NotRequired[str]
    r"""Battery capacity threshold for time slot 5 (%)"""
    cap6: NotRequired[str]
    r"""Battery capacity threshold for time slot 6 (%)"""
    sell_time1_volt: NotRequired[str]
    sell_time2_volt: NotRequired[str]
    sell_time3_volt: NotRequired[str]
    sell_time4_volt: NotRequired[str]
    sell_time5_volt: NotRequired[str]
    sell_time6_volt: NotRequired[str]
    zero_export_power: NotRequired[str]
    solar_max_sell_power: NotRequired[str]
    grid_peak_shaving: NotRequired[str]
    low_volt_cross_en: NotRequired[str]
    generator_start_cap: NotRequired[str]
    battery_low_cap: NotRequired[str]
    battery_restart_cap: NotRequired[str]
    r"""Battery restart SOC threshold (%)"""
    battery_shutdown_cap: NotRequired[str]
    r"""Battery shutdown SOC threshold (%)"""
    battery_max_current_charge: NotRequired[str]
    r"""Battery maximum charge current (A)"""
    battery_max_current_discharge: NotRequired[str]
    r"""Battery maximum discharge current (A)"""
    time1on: NotRequired[bool]
    r"""Enable time slot 1"""
    time2on: NotRequired[bool]
    r"""Enable time slot 2"""
    time3on: NotRequired[bool]
    r"""Enable time slot 3"""
    time4on: NotRequired[bool]
    r"""Enable time slot 4"""
    time5on: NotRequired[bool]
    r"""Enable time slot 5"""
    time6on: NotRequired[bool]
    r"""Enable time slot 6"""
    gen_time1on: NotRequired[bool]
    r"""Enable generator time slot 1"""
    gen_time2on: NotRequired[bool]
    r"""Enable generator time slot 2"""
    gen_time3on: NotRequired[bool]
    r"""Enable generator time slot 3"""
    gen_time4on: NotRequired[bool]
    r"""Enable generator time slot 4"""
    gen_time5on: NotRequired[bool]
    r"""Enable generator time slot 5"""
    gen_time6on: NotRequired[bool]
    r"""Enable generator time slot 6"""
    sell_time1on: NotRequired[bool]
    r"""Enable sell-to-grid for time slot 1"""
    sell_time2on: NotRequired[bool]
    r"""Enable sell-to-grid for time slot 2"""
    sell_time3on: NotRequired[bool]
    r"""Enable sell-to-grid for time slot 3"""
    sell_time4on: NotRequired[bool]
    r"""Enable sell-to-grid for time slot 4"""
    sell_time5on: NotRequired[bool]
    r"""Enable sell-to-grid for time slot 5"""
    sell_time6on: NotRequired[bool]
    r"""Enable sell-to-grid for time slot 6"""
    monday_on: NotRequired[bool]
    tuesday_on: NotRequired[bool]
    wednesday_on: NotRequired[bool]
    thursday_on: NotRequired[bool]
    friday_on: NotRequired[bool]
    saturday_on: NotRequired[bool]
    sunday_on: NotRequired[bool]


class InverterSettingsSet(BaseModel):
    r"""Inverter settings to update. All properties are optional — only included fields will be updated. This endpoint accepts partial requests."""

    sn: Optional[str] = None
    r"""Inverter serial number"""

    safety_type: Annotated[Optional[str], pydantic.Field(alias="safetyType")] = None

    batt_mode: Annotated[Optional[str], pydantic.Field(alias="battMode")] = None

    solar_sell: Annotated[Optional[str], pydantic.Field(alias="solarSell")] = None

    pv_max_limit: Annotated[Optional[str], pydantic.Field(alias="pvMaxLimit")] = None

    energy_mode: Annotated[Optional[str], pydantic.Field(alias="energyMode")] = None

    peak_and_vallery: Annotated[
        Optional[str], pydantic.Field(alias="peakAndVallery")
    ] = None

    sys_work_mode: Annotated[Optional[str], pydantic.Field(alias="sysWorkMode")] = None

    sell_time1: Annotated[Optional[str], pydantic.Field(alias="sellTime1")] = None
    r"""Time slot 1 start time (HH:MM)"""

    sell_time2: Annotated[Optional[str], pydantic.Field(alias="sellTime2")] = None
    r"""Time slot 2 start time (HH:MM)"""

    sell_time3: Annotated[Optional[str], pydantic.Field(alias="sellTime3")] = None
    r"""Time slot 3 start time (HH:MM)"""

    sell_time4: Annotated[Optional[str], pydantic.Field(alias="sellTime4")] = None
    r"""Time slot 4 start time (HH:MM)"""

    sell_time5: Annotated[Optional[str], pydantic.Field(alias="sellTime5")] = None
    r"""Time slot 5 start time (HH:MM)"""

    sell_time6: Annotated[Optional[str], pydantic.Field(alias="sellTime6")] = None
    r"""Time slot 6 start time (HH:MM)"""

    sell_time1_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime1Pac")] = (
        None
    )

    sell_time2_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime2Pac")] = (
        None
    )

    sell_time3_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime3Pac")] = (
        None
    )

    sell_time4_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime4Pac")] = (
        None
    )

    sell_time5_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime5Pac")] = (
        None
    )

    sell_time6_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime6Pac")] = (
        None
    )

    cap1: Optional[str] = None
    r"""Battery capacity threshold for time slot 1 (%)"""

    cap2: Optional[str] = None
    r"""Battery capacity threshold for time slot 2 (%)"""

    cap3: Optional[str] = None
    r"""Battery capacity threshold for time slot 3 (%)"""

    cap4: Optional[str] = None
    r"""Battery capacity threshold for time slot 4 (%)"""

    cap5: Optional[str] = None
    r"""Battery capacity threshold for time slot 5 (%)"""

    cap6: Optional[str] = None
    r"""Battery capacity threshold for time slot 6 (%)"""

    sell_time1_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime1Volt")] = (
        None
    )

    sell_time2_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime2Volt")] = (
        None
    )

    sell_time3_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime3Volt")] = (
        None
    )

    sell_time4_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime4Volt")] = (
        None
    )

    sell_time5_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime5Volt")] = (
        None
    )

    sell_time6_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime6Volt")] = (
        None
    )

    zero_export_power: Annotated[
        Optional[str], pydantic.Field(alias="zeroExportPower")
    ] = None

    solar_max_sell_power: Annotated[
        Optional[str], pydantic.Field(alias="solarMaxSellPower")
    ] = None

    grid_peak_shaving: Annotated[
        Optional[str], pydantic.Field(alias="gridPeakShaving")
    ] = None

    low_volt_cross_en: Annotated[
        Optional[str], pydantic.Field(alias="lowVoltCrossEn")
    ] = None

    generator_start_cap: Annotated[
        Optional[str], pydantic.Field(alias="generatorStartCap")
    ] = None

    battery_low_cap: Annotated[Optional[str], pydantic.Field(alias="batteryLowCap")] = (
        None
    )

    battery_restart_cap: Annotated[
        Optional[str], pydantic.Field(alias="batteryRestartCap")
    ] = None
    r"""Battery restart SOC threshold (%)"""

    battery_shutdown_cap: Annotated[
        Optional[str], pydantic.Field(alias="batteryShutdownCap")
    ] = None
    r"""Battery shutdown SOC threshold (%)"""

    battery_max_current_charge: Annotated[
        Optional[str], pydantic.Field(alias="batteryMaxCurrentCharge")
    ] = None
    r"""Battery maximum charge current (A)"""

    battery_max_current_discharge: Annotated[
        Optional[str], pydantic.Field(alias="batteryMaxCurrentDischarge")
    ] = None
    r"""Battery maximum discharge current (A)"""

    time1on: Optional[bool] = None
    r"""Enable time slot 1"""

    time2on: Optional[bool] = None
    r"""Enable time slot 2"""

    time3on: Optional[bool] = None
    r"""Enable time slot 3"""

    time4on: Optional[bool] = None
    r"""Enable time slot 4"""

    time5on: Optional[bool] = None
    r"""Enable time slot 5"""

    time6on: Optional[bool] = None
    r"""Enable time slot 6"""

    gen_time1on: Annotated[Optional[bool], pydantic.Field(alias="genTime1on")] = None
    r"""Enable generator time slot 1"""

    gen_time2on: Annotated[Optional[bool], pydantic.Field(alias="genTime2on")] = None
    r"""Enable generator time slot 2"""

    gen_time3on: Annotated[Optional[bool], pydantic.Field(alias="genTime3on")] = None
    r"""Enable generator time slot 3"""

    gen_time4on: Annotated[Optional[bool], pydantic.Field(alias="genTime4on")] = None
    r"""Enable generator time slot 4"""

    gen_time5on: Annotated[Optional[bool], pydantic.Field(alias="genTime5on")] = None
    r"""Enable generator time slot 5"""

    gen_time6on: Annotated[Optional[bool], pydantic.Field(alias="genTime6on")] = None
    r"""Enable generator time slot 6"""

    sell_time1on: Annotated[Optional[bool], pydantic.Field(alias="sellTime1on")] = None
    r"""Enable sell-to-grid for time slot 1"""

    sell_time2on: Annotated[Optional[bool], pydantic.Field(alias="sellTime2on")] = None
    r"""Enable sell-to-grid for time slot 2"""

    sell_time3on: Annotated[Optional[bool], pydantic.Field(alias="sellTime3on")] = None
    r"""Enable sell-to-grid for time slot 3"""

    sell_time4on: Annotated[Optional[bool], pydantic.Field(alias="sellTime4on")] = None
    r"""Enable sell-to-grid for time slot 4"""

    sell_time5on: Annotated[Optional[bool], pydantic.Field(alias="sellTime5on")] = None
    r"""Enable sell-to-grid for time slot 5"""

    sell_time6on: Annotated[Optional[bool], pydantic.Field(alias="sellTime6on")] = None
    r"""Enable sell-to-grid for time slot 6"""

    monday_on: Annotated[Optional[bool], pydantic.Field(alias="mondayOn")] = None

    tuesday_on: Annotated[Optional[bool], pydantic.Field(alias="tuesdayOn")] = None

    wednesday_on: Annotated[Optional[bool], pydantic.Field(alias="wednesdayOn")] = None

    thursday_on: Annotated[Optional[bool], pydantic.Field(alias="thursdayOn")] = None

    friday_on: Annotated[Optional[bool], pydantic.Field(alias="fridayOn")] = None

    saturday_on: Annotated[Optional[bool], pydantic.Field(alias="saturdayOn")] = None

    sunday_on: Annotated[Optional[bool], pydantic.Field(alias="sundayOn")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "sn",
                "safetyType",
                "battMode",
                "solarSell",
                "pvMaxLimit",
                "energyMode",
                "peakAndVallery",
                "sysWorkMode",
                "sellTime1",
                "sellTime2",
                "sellTime3",
                "sellTime4",
                "sellTime5",
                "sellTime6",
                "sellTime1Pac",
                "sellTime2Pac",
                "sellTime3Pac",
                "sellTime4Pac",
                "sellTime5Pac",
                "sellTime6Pac",
                "cap1",
                "cap2",
                "cap3",
                "cap4",
                "cap5",
                "cap6",
                "sellTime1Volt",
                "sellTime2Volt",
                "sellTime3Volt",
                "sellTime4Volt",
                "sellTime5Volt",
                "sellTime6Volt",
                "zeroExportPower",
                "solarMaxSellPower",
                "gridPeakShaving",
                "lowVoltCrossEn",
                "generatorStartCap",
                "batteryLowCap",
                "batteryRestartCap",
                "batteryShutdownCap",
                "batteryMaxCurrentCharge",
                "batteryMaxCurrentDischarge",
                "time1on",
                "time2on",
                "time3on",
                "time4on",
                "time5on",
                "time6on",
                "genTime1on",
                "genTime2on",
                "genTime3on",
                "genTime4on",
                "genTime5on",
                "genTime6on",
                "sellTime1on",
                "sellTime2on",
                "sellTime3on",
                "sellTime4on",
                "sellTime5on",
                "sellTime6on",
                "mondayOn",
                "tuesdayOn",
                "wednesdayOn",
                "thursdayOn",
                "fridayOn",
                "saturdayOn",
                "sundayOn",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    InverterSettingsSet.model_rebuild()
except NameError:
    pass
