"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InverterSettingsTypedDict(TypedDict):
    sell_time1: NotRequired[str]
    gen_time2on: NotRequired[str]
    beep: NotRequired[str]
    sell_time2: NotRequired[str]
    watt_over_exit_freq_stop_delay: NotRequired[str]
    sell_time5: NotRequired[str]
    sell_time6: NotRequired[str]
    sell_time3: NotRequired[str]
    sell_time4: NotRequired[str]
    ex_meter_ct_switch: NotRequired[str]
    sd_charge_on: NotRequired[str]
    lock_in_volt_var: NotRequired[str]
    time2on: NotRequired[str]
    bat_warn: NotRequired[str]
    watt_var_enable: NotRequired[str]
    reconn_min_volt: NotRequired[str]
    ca_f_start: NotRequired[str]
    pv_max_limit: NotRequired[str]
    sensors_check: NotRequired[str]
    under_freq2_delay: NotRequired[str]
    var_qac2: NotRequired[str]
    var_qac3: NotRequired[str]
    var_qac1: NotRequired[str]
    watt_under_exit_freq: NotRequired[str]
    over_volt1: NotRequired[str]
    over_volt2: NotRequired[str]
    var_qac4: NotRequired[str]
    gen_peak_power: NotRequired[str]
    meter_b: NotRequired[str]
    eeprom: NotRequired[str]
    meter_a: NotRequired[str]
    com_set: NotRequired[str]
    ca_volt_pressure_enable: NotRequired[str]
    meter_c: NotRequired[str]
    watt_under_freq1: NotRequired[str]
    solar_max_sell_power: NotRequired[str]
    ac_couple_on_grid_side_enable: NotRequired[str]
    thursday_on: NotRequired[str]
    time3_on: NotRequired[str]
    battery_restart_cap: NotRequired[str]
    over_freq1_delay: NotRequired[str]
    bms_err_stop: NotRequired[str]
    check_time: NotRequired[str]
    ac_output_power_limit: NotRequired[str]
    ats_switch: NotRequired[str]
    pv1_self_check: NotRequired[str]
    ac_current_up: NotRequired[str]
    rsd: NotRequired[str]
    battery_on: NotRequired[str]
    gen_time1on: NotRequired[str]
    volt12: NotRequired[str]
    volt10: NotRequired[str]
    volt11: NotRequired[str]
    time1on: NotRequired[str]
    watt_under_freq1_start_delay: NotRequired[str]
    rcd: NotRequired[str]
    charge_volt: NotRequired[str]
    wednesday_on: NotRequired[str]
    mppt_multi: NotRequired[str]
    float_volt: NotRequired[str]
    work_state: NotRequired[str]
    load_mode: NotRequired[str]
    sys_work_mode: NotRequired[str]
    sn: NotRequired[str]
    gen_cooling_time: NotRequired[str]
    gen_peak_shaving: NotRequired[str]
    off_grid_immediately_off: NotRequired[str]
    sell_time3_volt: NotRequired[str]
    sell_time2_pac: NotRequired[str]
    current12: NotRequired[str]
    time2_on: NotRequired[str]
    current10: NotRequired[str]
    current11: NotRequired[str]
    battery_efficiency: NotRequired[str]
    gen_and_grid_signal: NotRequired[str]
    pv3_self_check: NotRequired[str]
    watt_v4: NotRequired[str]
    ac_freq_low: NotRequired[str]
    watt_v2: NotRequired[str]
    watt_v3: NotRequired[str]
    watt_v1: NotRequired[str]
    battery_empty_v: NotRequired[str]
    open: NotRequired[str]
    reconn_max_freq: NotRequired[str]
    standard: NotRequired[str]
    watt_var_reactive2: NotRequired[str]
    disable_float_charge: NotRequired[str]
    inverter_type: NotRequired[str]
    watt_var_reactive3: NotRequired[str]
    watt_var_reactive4: NotRequired[str]
    solar_psu: NotRequired[str]
    friday_on: NotRequired[str]
    watt_var_reactive1: NotRequired[str]
    time4on: NotRequired[str]
    cap6: NotRequired[str]
    generator_forced_start: NotRequired[str]
    over_long_volt: NotRequired[str]
    cap4: NotRequired[str]
    cap5: NotRequired[str]
    battery_charge_type: NotRequired[str]
    gen_off_volt: NotRequired[str]
    cap2: NotRequired[str]
    cap3: NotRequired[str]
    absorption_volt: NotRequired[str]
    gen_to_load: NotRequired[str]
    mppt_num: NotRequired[str]
    under_freq2: NotRequired[str]
    under_freq1: NotRequired[str]
    watt_pf_enable: NotRequired[str]
    remote_lock: NotRequired[str]
    generator_start_cap: NotRequired[str]
    battery_max_current_charge: NotRequired[str]
    over_freq1: NotRequired[str]
    tuesday_on: NotRequired[str]
    gen_on_volt: NotRequired[str]
    over_freq2: NotRequired[str]
    solar2_wind_input_enable: NotRequired[str]
    ca_v_stop: NotRequired[str]
    time5_on: NotRequired[str]
    batt_mode: NotRequired[str]
    allow_remote_control: NotRequired[str]
    gen_on_cap: NotRequired[str]
    grid_always_on: NotRequired[str]
    battery_low_volt: NotRequired[str]
    ac_freq_up: NotRequired[str]
    cap1: NotRequired[str]
    charge_limit: NotRequired[str]
    generator_start_volt: NotRequired[str]
    over_volt1_delay: NotRequired[str]
    sell_time1_pac: NotRequired[str]
    california_freq_pressure_enable: NotRequired[str]
    active_power_control: NotRequired[str]
    battery_restart_volt: NotRequired[str]
    zero_export_power: NotRequired[str]
    over_volt2_delay: NotRequired[str]
    equ_charge_cycle: NotRequired[str]
    discharge_current: NotRequired[str]
    solar_sell: NotRequired[str]
    mppt_volt_low: NotRequired[str]
    time3on: NotRequired[str]
    watt_volt_enable: NotRequired[str]
    ca_fw_enable: NotRequired[str]
    max_operating_time_of_gen: NotRequired[str]
    mic_export_grid_off: NotRequired[str]
    import_power: NotRequired[str]
    pv_line: NotRequired[str]
    three41: NotRequired[str]
    ca_vw_enable: NotRequired[str]
    battery_shutdown_volt: NotRequired[str]
    volt3: NotRequired[str]
    volt4: NotRequired[str]
    volt1: NotRequired[str]
    volt2: NotRequired[str]
    start_volt_up: NotRequired[str]
    volt7: NotRequired[str]
    volt8: NotRequired[str]
    volt5: NotRequired[str]
    sell_time6_pac: NotRequired[str]
    volt6: NotRequired[str]
    time4_on: NotRequired[str]
    sell_time4_volt: NotRequired[str]
    volt9: NotRequired[str]
    fac_low_protect: NotRequired[str]
    watt_over_freq1: NotRequired[str]
    watt_pf4: NotRequired[str]
    low_noise_mode: NotRequired[str]
    tempco: NotRequired[str]
    arc_fact_frz: NotRequired[str]
    watt_pf1: NotRequired[str]
    watt_pf2: NotRequired[str]
    watt_pf3: NotRequired[str]
    meter_select: NotRequired[str]
    gen_charge_on: NotRequired[str]
    external_ct_ratio: NotRequired[str]
    grid_mode: NotRequired[str]
    sell_time5_pac: NotRequired[str]
    low_through: NotRequired[str]
    drm_enable: NotRequired[str]
    pv2_self_check: NotRequired[str]
    under_freq1_delay: NotRequired[str]
    energy_mode: NotRequired[str]
    ampm: NotRequired[str]
    grid_peak_shaving: NotRequired[str]
    time6on: NotRequired[str]
    fac: NotRequired[str]
    vac_low_protect: NotRequired[str]
    charge_current_limit: NotRequired[str]
    ca_lv3: NotRequired[str]
    sunday_on: NotRequired[str]
    gen_time6on: NotRequired[str]
    battery_impedance: NotRequired[str]
    safety_type: NotRequired[str]
    var_volt4: NotRequired[str]
    var_volt3: NotRequired[str]
    var_volt2: NotRequired[str]
    special_function: NotRequired[str]
    var_volt1: NotRequired[str]
    monday_on: NotRequired[str]
    comm_addr: NotRequired[str]
    saturday_on: NotRequired[str]
    discharge_limit: NotRequired[str]
    ats_enable: NotRequired[str]
    ex_meter_ct: NotRequired[str]
    over_freq2_delay: NotRequired[str]
    phase: NotRequired[str]
    auto_dim: NotRequired[str]
    battery_work_status: NotRequired[str]
    gen_to_load_on: NotRequired[str]
    time_sync: NotRequired[str]
    watt_over_wgral_freq: NotRequired[str]
    sd_battery_current: NotRequired[str]
    peak_and_vallery: NotRequired[str]
    battery_empty_volt: NotRequired[str]
    battery_low_cap: NotRequired[str]
    under_volt2_delay: NotRequired[str]
    equ_charge_time: NotRequired[str]
    batt_type: NotRequired[str]
    grid_peak_power: NotRequired[str]
    reset: NotRequired[str]
    vac_high_protect: NotRequired[str]
    gen_time5on: NotRequired[str]
    deye_gen_power_double_flag: NotRequired[str]
    pwm: NotRequired[str]
    time5on: NotRequired[str]
    high_through: NotRequired[str]
    lock_out_volt_var: NotRequired[str]
    lock_in_watt_pf: NotRequired[str]
    ca_v_start: NotRequired[str]
    ac_volt_up: NotRequired[str]
    watt_freq_enable: NotRequired[str]
    watt_over_exit_freq: NotRequired[str]
    sell_time5_volt: NotRequired[str]
    ca_f_stop: NotRequired[str]
    low_power_mode: NotRequired[str]
    var_volt_enable: NotRequired[str]
    ac_couple_freq_upper: NotRequired[str]
    impedance_low: NotRequired[str]
    ac_type: NotRequired[str]
    fac_high_protect: NotRequired[str]
    recovery_time: NotRequired[str]
    under_volt2: NotRequired[str]
    lithium_mode: NotRequired[str]
    under_volt1: NotRequired[str]
    grid_signal: NotRequired[str]
    watt_over_freq1_start_delay: NotRequired[str]
    test_command: NotRequired[str]
    time6_on: NotRequired[str]
    signal_island_mode_enable: NotRequired[str]
    ups_standard: NotRequired[str]
    reconn_min_freq: NotRequired[str]
    parallel_register2: NotRequired[str]
    parallel_register1: NotRequired[str]
    start_volt_low: NotRequired[str]
    smart_load_open_delay: NotRequired[str]
    gen_time4on: NotRequired[str]
    sell_time1_volt: NotRequired[str]
    watt_var_active4: NotRequired[str]
    watt_var_active3: NotRequired[str]
    gen_connect_grid: NotRequired[str]
    flag2: NotRequired[str]
    soft_start: NotRequired[str]
    lock_out_watt_pf: NotRequired[str]
    sd_start_cap: NotRequired[str]
    current4: NotRequired[str]
    current3: NotRequired[str]
    current2: NotRequired[str]
    current1: NotRequired[str]
    gfdi: NotRequired[str]
    current8: NotRequired[str]
    current7: NotRequired[str]
    current6: NotRequired[str]
    current5: NotRequired[str]
    check_self_time: NotRequired[str]
    limit: NotRequired[str]
    watt_w3: NotRequired[str]
    watt_var_active2: NotRequired[str]
    watt_w4: NotRequired[str]
    watt_var_active1: NotRequired[str]
    external_current: NotRequired[str]
    watt_w1: NotRequired[str]
    watt_w2: NotRequired[str]
    vn_response_time: NotRequired[str]
    battery_shutdown_cap: NotRequired[str]
    watt_under_exit_freq_stop_delay: NotRequired[str]
    offset: NotRequired[str]
    sell_time4_pac: NotRequired[str]
    watt_active_pf1: NotRequired[str]
    current9: NotRequired[str]
    discharge_volt: NotRequired[str]
    qv_response_time: NotRequired[str]
    watt_active_pf4: NotRequired[str]
    time1_on: NotRequired[str]
    watt_active_pf2: NotRequired[str]
    four19: NotRequired[str]
    watt_active_pf3: NotRequired[str]
    mic_export_all: NotRequired[str]
    battery_max_current_discharge: NotRequired[str]
    islet_protect: NotRequired[str]
    lock_out_change: NotRequired[str]
    california_volt_pressure_enable: NotRequired[str]
    equ_volt_charge: NotRequired[str]
    battery_cap: NotRequired[str]
    gen_off_cap: NotRequired[str]
    gen_time3on: NotRequired[str]
    sell_time6_volt: NotRequired[str]
    sell_time3_pac: NotRequired[str]
    ac_couple_on_load_side_enable: NotRequired[str]
    sd_start_volt: NotRequired[str]
    generator_battery_current: NotRequired[str]
    reconn_max_volt: NotRequired[str]
    modbus_sn: NotRequired[str]
    inverter_output_voltage: NotRequired[str]
    charge_current: NotRequired[str]
    solar1_wind_input_enable: NotRequired[str]
    dc_volt_up: NotRequired[str]
    parallel: NotRequired[str]
    limter: NotRequired[str]
    bat_err: NotRequired[str]
    backup_delay: NotRequired[str]
    discharge_current_limit: NotRequired[str]
    arc_fact_t: NotRequired[str]
    watt_under_wgal_freq: NotRequired[str]
    comm_baud_rate: NotRequired[str]
    equip_mode: NotRequired[str]
    grid_side_inv_meter2: NotRequired[str]
    under_volt1_delay: NotRequired[str]
    arc_fault_type: NotRequired[str]
    arc_fact_b: NotRequired[str]
    normal_upward_slope: NotRequired[str]
    arc_fact_c: NotRequired[str]
    pf: NotRequired[str]
    arc_fact_d: NotRequired[str]
    gen_min_solar: NotRequired[str]
    sell_time2_volt: NotRequired[str]
    arc_fact_f: NotRequired[str]
    arc_fact_i: NotRequired[str]
    ac_volt_low: NotRequired[str]
    gen_signal: NotRequired[str]


class InverterSettings(BaseModel):
    sell_time1: Annotated[Optional[str], pydantic.Field(alias="sellTime1")] = None

    gen_time2on: Annotated[Optional[str], pydantic.Field(alias="genTime2on")] = None

    beep: Optional[str] = None

    sell_time2: Annotated[Optional[str], pydantic.Field(alias="sellTime2")] = None

    watt_over_exit_freq_stop_delay: Annotated[
        Optional[str], pydantic.Field(alias="wattOverExitFreqStopDelay")
    ] = None

    sell_time5: Annotated[Optional[str], pydantic.Field(alias="sellTime5")] = None

    sell_time6: Annotated[Optional[str], pydantic.Field(alias="sellTime6")] = None

    sell_time3: Annotated[Optional[str], pydantic.Field(alias="sellTime3")] = None

    sell_time4: Annotated[Optional[str], pydantic.Field(alias="sellTime4")] = None

    ex_meter_ct_switch: Annotated[
        Optional[str], pydantic.Field(alias="exMeterCtSwitch")
    ] = None

    sd_charge_on: Annotated[Optional[str], pydantic.Field(alias="sdChargeOn")] = None

    lock_in_volt_var: Annotated[
        Optional[str], pydantic.Field(alias="lockInVoltVar")
    ] = None

    time2on: Optional[str] = None

    bat_warn: Annotated[Optional[str], pydantic.Field(alias="batWarn")] = None

    watt_var_enable: Annotated[Optional[str], pydantic.Field(alias="wattVarEnable")] = (
        None
    )

    reconn_min_volt: Annotated[Optional[str], pydantic.Field(alias="reconnMinVolt")] = (
        None
    )

    ca_f_start: Annotated[Optional[str], pydantic.Field(alias="caFStart")] = None

    pv_max_limit: Annotated[Optional[str], pydantic.Field(alias="pvMaxLimit")] = None

    sensors_check: Annotated[Optional[str], pydantic.Field(alias="sensorsCheck")] = None

    under_freq2_delay: Annotated[
        Optional[str], pydantic.Field(alias="underFreq2Delay")
    ] = None

    var_qac2: Annotated[Optional[str], pydantic.Field(alias="varQac2")] = None

    var_qac3: Annotated[Optional[str], pydantic.Field(alias="varQac3")] = None

    var_qac1: Annotated[Optional[str], pydantic.Field(alias="varQac1")] = None

    watt_under_exit_freq: Annotated[
        Optional[str], pydantic.Field(alias="wattUnderExitFreq")
    ] = None

    over_volt1: Annotated[Optional[str], pydantic.Field(alias="overVolt1")] = None

    over_volt2: Annotated[Optional[str], pydantic.Field(alias="overVolt2")] = None

    var_qac4: Annotated[Optional[str], pydantic.Field(alias="varQac4")] = None

    gen_peak_power: Annotated[Optional[str], pydantic.Field(alias="genPeakPower")] = (
        None
    )

    meter_b: Annotated[Optional[str], pydantic.Field(alias="meterB")] = None

    eeprom: Optional[str] = None

    meter_a: Annotated[Optional[str], pydantic.Field(alias="meterA")] = None

    com_set: Annotated[Optional[str], pydantic.Field(alias="comSet")] = None

    ca_volt_pressure_enable: Annotated[
        Optional[str], pydantic.Field(alias="caVoltPressureEnable")
    ] = None

    meter_c: Annotated[Optional[str], pydantic.Field(alias="meterC")] = None

    watt_under_freq1: Annotated[
        Optional[str], pydantic.Field(alias="wattUnderFreq1")
    ] = None

    solar_max_sell_power: Annotated[
        Optional[str], pydantic.Field(alias="solarMaxSellPower")
    ] = None

    ac_couple_on_grid_side_enable: Annotated[
        Optional[str], pydantic.Field(alias="acCoupleOnGridSideEnable")
    ] = None

    thursday_on: Annotated[Optional[str], pydantic.Field(alias="thursdayOn")] = None

    time3_on: Annotated[Optional[str], pydantic.Field(alias="time3On")] = None

    battery_restart_cap: Annotated[
        Optional[str], pydantic.Field(alias="batteryRestartCap")
    ] = None

    over_freq1_delay: Annotated[
        Optional[str], pydantic.Field(alias="overFreq1Delay")
    ] = None

    bms_err_stop: Annotated[Optional[str], pydantic.Field(alias="bmsErrStop")] = None

    check_time: Annotated[Optional[str], pydantic.Field(alias="checkTime")] = None

    ac_output_power_limit: Annotated[
        Optional[str], pydantic.Field(alias="acOutputPowerLimit")
    ] = None

    ats_switch: Annotated[Optional[str], pydantic.Field(alias="atsSwitch")] = None

    pv1_self_check: Annotated[Optional[str], pydantic.Field(alias="pv1SelfCheck")] = (
        None
    )

    ac_current_up: Annotated[Optional[str], pydantic.Field(alias="acCurrentUp")] = None

    rsd: Optional[str] = None

    battery_on: Annotated[Optional[str], pydantic.Field(alias="batteryOn")] = None

    gen_time1on: Annotated[Optional[str], pydantic.Field(alias="genTime1on")] = None

    volt12: Optional[str] = None

    volt10: Optional[str] = None

    volt11: Optional[str] = None

    time1on: Optional[str] = None

    watt_under_freq1_start_delay: Annotated[
        Optional[str], pydantic.Field(alias="wattUnderFreq1StartDelay")
    ] = None

    rcd: Optional[str] = None

    charge_volt: Annotated[Optional[str], pydantic.Field(alias="chargeVolt")] = None

    wednesday_on: Annotated[Optional[str], pydantic.Field(alias="wednesdayOn")] = None

    mppt_multi: Annotated[Optional[str], pydantic.Field(alias="mpptMulti")] = None

    float_volt: Annotated[Optional[str], pydantic.Field(alias="floatVolt")] = None

    work_state: Annotated[Optional[str], pydantic.Field(alias="workState")] = None

    load_mode: Annotated[Optional[str], pydantic.Field(alias="loadMode")] = None

    sys_work_mode: Annotated[Optional[str], pydantic.Field(alias="sysWorkMode")] = None

    sn: Optional[str] = None

    gen_cooling_time: Annotated[
        Optional[str], pydantic.Field(alias="genCoolingTime")
    ] = None

    gen_peak_shaving: Annotated[
        Optional[str], pydantic.Field(alias="genPeakShaving")
    ] = None

    off_grid_immediately_off: Annotated[
        Optional[str], pydantic.Field(alias="offGridImmediatelyOff")
    ] = None

    sell_time3_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime3Volt")] = (
        None
    )

    sell_time2_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime2Pac")] = (
        None
    )

    current12: Optional[str] = None

    time2_on: Annotated[Optional[str], pydantic.Field(alias="time2On")] = None

    current10: Optional[str] = None

    current11: Optional[str] = None

    battery_efficiency: Annotated[
        Optional[str], pydantic.Field(alias="batteryEfficiency")
    ] = None

    gen_and_grid_signal: Annotated[
        Optional[str], pydantic.Field(alias="genAndGridSignal")
    ] = None

    pv3_self_check: Annotated[Optional[str], pydantic.Field(alias="pv3SelfCheck")] = (
        None
    )

    watt_v4: Annotated[Optional[str], pydantic.Field(alias="wattV4")] = None

    ac_freq_low: Annotated[Optional[str], pydantic.Field(alias="acFreqLow")] = None

    watt_v2: Annotated[Optional[str], pydantic.Field(alias="wattV2")] = None

    watt_v3: Annotated[Optional[str], pydantic.Field(alias="wattV3")] = None

    watt_v1: Annotated[Optional[str], pydantic.Field(alias="wattV1")] = None

    battery_empty_v: Annotated[Optional[str], pydantic.Field(alias="batteryEmptyV")] = (
        None
    )

    open: Optional[str] = None

    reconn_max_freq: Annotated[Optional[str], pydantic.Field(alias="reconnMaxFreq")] = (
        None
    )

    standard: Optional[str] = None

    watt_var_reactive2: Annotated[
        Optional[str], pydantic.Field(alias="wattVarReactive2")
    ] = None

    disable_float_charge: Annotated[
        Optional[str], pydantic.Field(alias="disableFloatCharge")
    ] = None

    inverter_type: Annotated[Optional[str], pydantic.Field(alias="inverterType")] = None

    watt_var_reactive3: Annotated[
        Optional[str], pydantic.Field(alias="wattVarReactive3")
    ] = None

    watt_var_reactive4: Annotated[
        Optional[str], pydantic.Field(alias="wattVarReactive4")
    ] = None

    solar_psu: Annotated[Optional[str], pydantic.Field(alias="solarPSU")] = None

    friday_on: Annotated[Optional[str], pydantic.Field(alias="fridayOn")] = None

    watt_var_reactive1: Annotated[
        Optional[str], pydantic.Field(alias="wattVarReactive1")
    ] = None

    time4on: Optional[str] = None

    cap6: Optional[str] = None

    generator_forced_start: Annotated[
        Optional[str], pydantic.Field(alias="generatorForcedStart")
    ] = None

    over_long_volt: Annotated[Optional[str], pydantic.Field(alias="overLongVolt")] = (
        None
    )

    cap4: Optional[str] = None

    cap5: Optional[str] = None

    battery_charge_type: Annotated[
        Optional[str], pydantic.Field(alias="batteryChargeType")
    ] = None

    gen_off_volt: Annotated[Optional[str], pydantic.Field(alias="genOffVolt")] = None

    cap2: Optional[str] = None

    cap3: Optional[str] = None

    absorption_volt: Annotated[
        Optional[str], pydantic.Field(alias="absorptionVolt")
    ] = None

    gen_to_load: Annotated[Optional[str], pydantic.Field(alias="genToLoad")] = None

    mppt_num: Annotated[Optional[str], pydantic.Field(alias="mpptNum")] = None

    under_freq2: Annotated[Optional[str], pydantic.Field(alias="underFreq2")] = None

    under_freq1: Annotated[Optional[str], pydantic.Field(alias="underFreq1")] = None

    watt_pf_enable: Annotated[Optional[str], pydantic.Field(alias="wattPfEnable")] = (
        None
    )

    remote_lock: Annotated[Optional[str], pydantic.Field(alias="remoteLock")] = None

    generator_start_cap: Annotated[
        Optional[str], pydantic.Field(alias="generatorStartCap")
    ] = None

    battery_max_current_charge: Annotated[
        Optional[str], pydantic.Field(alias="batteryMaxCurrentCharge")
    ] = None

    over_freq1: Annotated[Optional[str], pydantic.Field(alias="overFreq1")] = None

    tuesday_on: Annotated[Optional[str], pydantic.Field(alias="tuesdayOn")] = None

    gen_on_volt: Annotated[Optional[str], pydantic.Field(alias="genOnVolt")] = None

    over_freq2: Annotated[Optional[str], pydantic.Field(alias="overFreq2")] = None

    solar2_wind_input_enable: Annotated[
        Optional[str], pydantic.Field(alias="solar2WindInputEnable")
    ] = None

    ca_v_stop: Annotated[Optional[str], pydantic.Field(alias="caVStop")] = None

    time5_on: Annotated[Optional[str], pydantic.Field(alias="time5On")] = None

    batt_mode: Annotated[Optional[str], pydantic.Field(alias="battMode")] = None

    allow_remote_control: Annotated[
        Optional[str], pydantic.Field(alias="allowRemoteControl")
    ] = None

    gen_on_cap: Annotated[Optional[str], pydantic.Field(alias="genOnCap")] = None

    grid_always_on: Annotated[Optional[str], pydantic.Field(alias="gridAlwaysOn")] = (
        None
    )

    battery_low_volt: Annotated[
        Optional[str], pydantic.Field(alias="batteryLowVolt")
    ] = None

    ac_freq_up: Annotated[Optional[str], pydantic.Field(alias="acFreqUp")] = None

    cap1: Optional[str] = None

    charge_limit: Annotated[Optional[str], pydantic.Field(alias="chargeLimit")] = None

    generator_start_volt: Annotated[
        Optional[str], pydantic.Field(alias="generatorStartVolt")
    ] = None

    over_volt1_delay: Annotated[
        Optional[str], pydantic.Field(alias="overVolt1Delay")
    ] = None

    sell_time1_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime1Pac")] = (
        None
    )

    california_freq_pressure_enable: Annotated[
        Optional[str], pydantic.Field(alias="californiaFreqPressureEnable")
    ] = None

    active_power_control: Annotated[
        Optional[str], pydantic.Field(alias="activePowerControl")
    ] = None

    battery_restart_volt: Annotated[
        Optional[str], pydantic.Field(alias="batteryRestartVolt")
    ] = None

    zero_export_power: Annotated[
        Optional[str], pydantic.Field(alias="zeroExportPower")
    ] = None

    over_volt2_delay: Annotated[
        Optional[str], pydantic.Field(alias="overVolt2Delay")
    ] = None

    equ_charge_cycle: Annotated[
        Optional[str], pydantic.Field(alias="equChargeCycle")
    ] = None

    discharge_current: Annotated[
        Optional[str], pydantic.Field(alias="dischargeCurrent")
    ] = None

    solar_sell: Annotated[Optional[str], pydantic.Field(alias="solarSell")] = None

    mppt_volt_low: Annotated[Optional[str], pydantic.Field(alias="mpptVoltLow")] = None

    time3on: Optional[str] = None

    watt_volt_enable: Annotated[
        Optional[str], pydantic.Field(alias="wattVoltEnable")
    ] = None

    ca_fw_enable: Annotated[Optional[str], pydantic.Field(alias="caFwEnable")] = None

    max_operating_time_of_gen: Annotated[
        Optional[str], pydantic.Field(alias="maxOperatingTimeOfGen")
    ] = None

    mic_export_grid_off: Annotated[
        Optional[str], pydantic.Field(alias="micExportGridOff")
    ] = None

    import_power: Annotated[Optional[str], pydantic.Field(alias="importPower")] = None

    pv_line: Annotated[Optional[str], pydantic.Field(alias="pvLine")] = None

    three41: Optional[str] = None

    ca_vw_enable: Annotated[Optional[str], pydantic.Field(alias="caVwEnable")] = None

    battery_shutdown_volt: Annotated[
        Optional[str], pydantic.Field(alias="batteryShutdownVolt")
    ] = None

    volt3: Optional[str] = None

    volt4: Optional[str] = None

    volt1: Optional[str] = None

    volt2: Optional[str] = None

    start_volt_up: Annotated[Optional[str], pydantic.Field(alias="startVoltUp")] = None

    volt7: Optional[str] = None

    volt8: Optional[str] = None

    volt5: Optional[str] = None

    sell_time6_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime6Pac")] = (
        None
    )

    volt6: Optional[str] = None

    time4_on: Annotated[Optional[str], pydantic.Field(alias="time4On")] = None

    sell_time4_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime4Volt")] = (
        None
    )

    volt9: Optional[str] = None

    fac_low_protect: Annotated[Optional[str], pydantic.Field(alias="facLowProtect")] = (
        None
    )

    watt_over_freq1: Annotated[Optional[str], pydantic.Field(alias="wattOverFreq1")] = (
        None
    )

    watt_pf4: Annotated[Optional[str], pydantic.Field(alias="wattPf4")] = None

    low_noise_mode: Annotated[Optional[str], pydantic.Field(alias="lowNoiseMode")] = (
        None
    )

    tempco: Optional[str] = None

    arc_fact_frz: Annotated[Optional[str], pydantic.Field(alias="arcFactFrz")] = None

    watt_pf1: Annotated[Optional[str], pydantic.Field(alias="wattPf1")] = None

    watt_pf2: Annotated[Optional[str], pydantic.Field(alias="wattPf2")] = None

    watt_pf3: Annotated[Optional[str], pydantic.Field(alias="wattPf3")] = None

    meter_select: Annotated[Optional[str], pydantic.Field(alias="meterSelect")] = None

    gen_charge_on: Annotated[Optional[str], pydantic.Field(alias="genChargeOn")] = None

    external_ct_ratio: Annotated[
        Optional[str], pydantic.Field(alias="externalCtRatio")
    ] = None

    grid_mode: Annotated[Optional[str], pydantic.Field(alias="gridMode")] = None

    sell_time5_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime5Pac")] = (
        None
    )

    low_through: Annotated[Optional[str], pydantic.Field(alias="lowThrough")] = None

    drm_enable: Annotated[Optional[str], pydantic.Field(alias="drmEnable")] = None

    pv2_self_check: Annotated[Optional[str], pydantic.Field(alias="pv2SelfCheck")] = (
        None
    )

    under_freq1_delay: Annotated[
        Optional[str], pydantic.Field(alias="underFreq1Delay")
    ] = None

    energy_mode: Annotated[Optional[str], pydantic.Field(alias="energyMode")] = None

    ampm: Optional[str] = None

    grid_peak_shaving: Annotated[
        Optional[str], pydantic.Field(alias="gridPeakShaving")
    ] = None

    time6on: Optional[str] = None

    fac: Optional[str] = None

    vac_low_protect: Annotated[Optional[str], pydantic.Field(alias="vacLowProtect")] = (
        None
    )

    charge_current_limit: Annotated[
        Optional[str], pydantic.Field(alias="chargeCurrentLimit")
    ] = None

    ca_lv3: Annotated[Optional[str], pydantic.Field(alias="caLv3")] = None

    sunday_on: Annotated[Optional[str], pydantic.Field(alias="sundayOn")] = None

    gen_time6on: Annotated[Optional[str], pydantic.Field(alias="genTime6on")] = None

    battery_impedance: Annotated[
        Optional[str], pydantic.Field(alias="batteryImpedance")
    ] = None

    safety_type: Annotated[Optional[str], pydantic.Field(alias="safetyType")] = None

    var_volt4: Annotated[Optional[str], pydantic.Field(alias="varVolt4")] = None

    var_volt3: Annotated[Optional[str], pydantic.Field(alias="varVolt3")] = None

    var_volt2: Annotated[Optional[str], pydantic.Field(alias="varVolt2")] = None

    special_function: Annotated[
        Optional[str], pydantic.Field(alias="specialFunction")
    ] = None

    var_volt1: Annotated[Optional[str], pydantic.Field(alias="varVolt1")] = None

    monday_on: Annotated[Optional[str], pydantic.Field(alias="mondayOn")] = None

    comm_addr: Annotated[Optional[str], pydantic.Field(alias="commAddr")] = None

    saturday_on: Annotated[Optional[str], pydantic.Field(alias="saturdayOn")] = None

    discharge_limit: Annotated[
        Optional[str], pydantic.Field(alias="dischargeLimit")
    ] = None

    ats_enable: Annotated[Optional[str], pydantic.Field(alias="atsEnable")] = None

    ex_meter_ct: Annotated[Optional[str], pydantic.Field(alias="exMeterCt")] = None

    over_freq2_delay: Annotated[
        Optional[str], pydantic.Field(alias="overFreq2Delay")
    ] = None

    phase: Optional[str] = None

    auto_dim: Annotated[Optional[str], pydantic.Field(alias="autoDim")] = None

    battery_work_status: Annotated[
        Optional[str], pydantic.Field(alias="batteryWorkStatus")
    ] = None

    gen_to_load_on: Annotated[Optional[str], pydantic.Field(alias="genToLoadOn")] = None

    time_sync: Annotated[Optional[str], pydantic.Field(alias="timeSync")] = None

    watt_over_wgral_freq: Annotated[
        Optional[str], pydantic.Field(alias="wattOverWgralFreq")
    ] = None

    sd_battery_current: Annotated[
        Optional[str], pydantic.Field(alias="sdBatteryCurrent")
    ] = None

    peak_and_vallery: Annotated[
        Optional[str], pydantic.Field(alias="peakAndVallery")
    ] = None

    battery_empty_volt: Annotated[
        Optional[str], pydantic.Field(alias="batteryEmptyVolt")
    ] = None

    battery_low_cap: Annotated[Optional[str], pydantic.Field(alias="batteryLowCap")] = (
        None
    )

    under_volt2_delay: Annotated[
        Optional[str], pydantic.Field(alias="underVolt2Delay")
    ] = None

    equ_charge_time: Annotated[Optional[str], pydantic.Field(alias="equChargeTime")] = (
        None
    )

    batt_type: Annotated[Optional[str], pydantic.Field(alias="battType")] = None

    grid_peak_power: Annotated[Optional[str], pydantic.Field(alias="gridPeakPower")] = (
        None
    )

    reset: Optional[str] = None

    vac_high_protect: Annotated[
        Optional[str], pydantic.Field(alias="vacHighProtect")
    ] = None

    gen_time5on: Annotated[Optional[str], pydantic.Field(alias="genTime5on")] = None

    deye_gen_power_double_flag: Annotated[
        Optional[str], pydantic.Field(alias="deyeGenPowerDoubleFlag")
    ] = None

    pwm: Optional[str] = None

    time5on: Optional[str] = None

    high_through: Annotated[Optional[str], pydantic.Field(alias="highThrough")] = None

    lock_out_volt_var: Annotated[
        Optional[str], pydantic.Field(alias="lockOutVoltVar")
    ] = None

    lock_in_watt_pf: Annotated[Optional[str], pydantic.Field(alias="lockInWattPF")] = (
        None
    )

    ca_v_start: Annotated[Optional[str], pydantic.Field(alias="caVStart")] = None

    ac_volt_up: Annotated[Optional[str], pydantic.Field(alias="acVoltUp")] = None

    watt_freq_enable: Annotated[
        Optional[str], pydantic.Field(alias="wattFreqEnable")
    ] = None

    watt_over_exit_freq: Annotated[
        Optional[str], pydantic.Field(alias="wattOverExitFreq")
    ] = None

    sell_time5_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime5Volt")] = (
        None
    )

    ca_f_stop: Annotated[Optional[str], pydantic.Field(alias="caFStop")] = None

    low_power_mode: Annotated[Optional[str], pydantic.Field(alias="lowPowerMode")] = (
        None
    )

    var_volt_enable: Annotated[Optional[str], pydantic.Field(alias="varVoltEnable")] = (
        None
    )

    ac_couple_freq_upper: Annotated[
        Optional[str], pydantic.Field(alias="acCoupleFreqUpper")
    ] = None

    impedance_low: Annotated[Optional[str], pydantic.Field(alias="impedanceLow")] = None

    ac_type: Annotated[Optional[str], pydantic.Field(alias="acType")] = None

    fac_high_protect: Annotated[
        Optional[str], pydantic.Field(alias="facHighProtect")
    ] = None

    recovery_time: Annotated[Optional[str], pydantic.Field(alias="recoveryTime")] = None

    under_volt2: Annotated[Optional[str], pydantic.Field(alias="underVolt2")] = None

    lithium_mode: Annotated[Optional[str], pydantic.Field(alias="lithiumMode")] = None

    under_volt1: Annotated[Optional[str], pydantic.Field(alias="underVolt1")] = None

    grid_signal: Annotated[Optional[str], pydantic.Field(alias="gridSignal")] = None

    watt_over_freq1_start_delay: Annotated[
        Optional[str], pydantic.Field(alias="wattOverFreq1StartDelay")
    ] = None

    test_command: Annotated[Optional[str], pydantic.Field(alias="testCommand")] = None

    time6_on: Annotated[Optional[str], pydantic.Field(alias="time6On")] = None

    signal_island_mode_enable: Annotated[
        Optional[str], pydantic.Field(alias="signalIslandModeEnable")
    ] = None

    ups_standard: Annotated[Optional[str], pydantic.Field(alias="upsStandard")] = None

    reconn_min_freq: Annotated[Optional[str], pydantic.Field(alias="reconnMinFreq")] = (
        None
    )

    parallel_register2: Annotated[
        Optional[str], pydantic.Field(alias="parallelRegister2")
    ] = None

    parallel_register1: Annotated[
        Optional[str], pydantic.Field(alias="parallelRegister1")
    ] = None

    start_volt_low: Annotated[Optional[str], pydantic.Field(alias="startVoltLow")] = (
        None
    )

    smart_load_open_delay: Annotated[
        Optional[str], pydantic.Field(alias="smartLoadOpenDelay")
    ] = None

    gen_time4on: Annotated[Optional[str], pydantic.Field(alias="genTime4on")] = None

    sell_time1_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime1Volt")] = (
        None
    )

    watt_var_active4: Annotated[
        Optional[str], pydantic.Field(alias="wattVarActive4")
    ] = None

    watt_var_active3: Annotated[
        Optional[str], pydantic.Field(alias="wattVarActive3")
    ] = None

    gen_connect_grid: Annotated[
        Optional[str], pydantic.Field(alias="genConnectGrid")
    ] = None

    flag2: Optional[str] = None

    soft_start: Annotated[Optional[str], pydantic.Field(alias="softStart")] = None

    lock_out_watt_pf: Annotated[
        Optional[str], pydantic.Field(alias="lockOutWattPF")
    ] = None

    sd_start_cap: Annotated[Optional[str], pydantic.Field(alias="sdStartCap")] = None

    current4: Optional[str] = None

    current3: Optional[str] = None

    current2: Optional[str] = None

    current1: Optional[str] = None

    gfdi: Optional[str] = None

    current8: Optional[str] = None

    current7: Optional[str] = None

    current6: Optional[str] = None

    current5: Optional[str] = None

    check_self_time: Annotated[Optional[str], pydantic.Field(alias="checkSelfTime")] = (
        None
    )

    limit: Optional[str] = None

    watt_w3: Annotated[Optional[str], pydantic.Field(alias="wattW3")] = None

    watt_var_active2: Annotated[
        Optional[str], pydantic.Field(alias="wattVarActive2")
    ] = None

    watt_w4: Annotated[Optional[str], pydantic.Field(alias="wattW4")] = None

    watt_var_active1: Annotated[
        Optional[str], pydantic.Field(alias="wattVarActive1")
    ] = None

    external_current: Annotated[
        Optional[str], pydantic.Field(alias="externalCurrent")
    ] = None

    watt_w1: Annotated[Optional[str], pydantic.Field(alias="wattW1")] = None

    watt_w2: Annotated[Optional[str], pydantic.Field(alias="wattW2")] = None

    vn_response_time: Annotated[
        Optional[str], pydantic.Field(alias="vnResponseTime")
    ] = None

    battery_shutdown_cap: Annotated[
        Optional[str], pydantic.Field(alias="batteryShutdownCap")
    ] = None

    watt_under_exit_freq_stop_delay: Annotated[
        Optional[str], pydantic.Field(alias="wattUnderExitFreqStopDelay")
    ] = None

    offset: Optional[str] = None

    sell_time4_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime4Pac")] = (
        None
    )

    watt_active_pf1: Annotated[Optional[str], pydantic.Field(alias="wattActivePf1")] = (
        None
    )

    current9: Optional[str] = None

    discharge_volt: Annotated[Optional[str], pydantic.Field(alias="dischargeVolt")] = (
        None
    )

    qv_response_time: Annotated[
        Optional[str], pydantic.Field(alias="qvResponseTime")
    ] = None

    watt_active_pf4: Annotated[Optional[str], pydantic.Field(alias="wattActivePf4")] = (
        None
    )

    time1_on: Annotated[Optional[str], pydantic.Field(alias="time1On")] = None

    watt_active_pf2: Annotated[Optional[str], pydantic.Field(alias="wattActivePf2")] = (
        None
    )

    four19: Optional[str] = None

    watt_active_pf3: Annotated[Optional[str], pydantic.Field(alias="wattActivePf3")] = (
        None
    )

    mic_export_all: Annotated[Optional[str], pydantic.Field(alias="micExportAll")] = (
        None
    )

    battery_max_current_discharge: Annotated[
        Optional[str], pydantic.Field(alias="batteryMaxCurrentDischarge")
    ] = None

    islet_protect: Annotated[Optional[str], pydantic.Field(alias="isletProtect")] = None

    lock_out_change: Annotated[Optional[str], pydantic.Field(alias="lockOutChange")] = (
        None
    )

    california_volt_pressure_enable: Annotated[
        Optional[str], pydantic.Field(alias="californiaVoltPressureEnable")
    ] = None

    equ_volt_charge: Annotated[Optional[str], pydantic.Field(alias="equVoltCharge")] = (
        None
    )

    battery_cap: Annotated[Optional[str], pydantic.Field(alias="batteryCap")] = None

    gen_off_cap: Annotated[Optional[str], pydantic.Field(alias="genOffCap")] = None

    gen_time3on: Annotated[Optional[str], pydantic.Field(alias="genTime3on")] = None

    sell_time6_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime6Volt")] = (
        None
    )

    sell_time3_pac: Annotated[Optional[str], pydantic.Field(alias="sellTime3Pac")] = (
        None
    )

    ac_couple_on_load_side_enable: Annotated[
        Optional[str], pydantic.Field(alias="acCoupleOnLoadSideEnable")
    ] = None

    sd_start_volt: Annotated[Optional[str], pydantic.Field(alias="sdStartVolt")] = None

    generator_battery_current: Annotated[
        Optional[str], pydantic.Field(alias="generatorBatteryCurrent")
    ] = None

    reconn_max_volt: Annotated[Optional[str], pydantic.Field(alias="reconnMaxVolt")] = (
        None
    )

    modbus_sn: Annotated[Optional[str], pydantic.Field(alias="modbusSn")] = None

    inverter_output_voltage: Annotated[
        Optional[str], pydantic.Field(alias="inverterOutputVoltage")
    ] = None

    charge_current: Annotated[Optional[str], pydantic.Field(alias="chargeCurrent")] = (
        None
    )

    solar1_wind_input_enable: Annotated[
        Optional[str], pydantic.Field(alias="solar1WindInputEnable")
    ] = None

    dc_volt_up: Annotated[Optional[str], pydantic.Field(alias="dcVoltUp")] = None

    parallel: Optional[str] = None

    limter: Optional[str] = None

    bat_err: Annotated[Optional[str], pydantic.Field(alias="batErr")] = None

    backup_delay: Annotated[Optional[str], pydantic.Field(alias="backupDelay")] = None

    discharge_current_limit: Annotated[
        Optional[str], pydantic.Field(alias="dischargeCurrentLimit")
    ] = None

    arc_fact_t: Annotated[Optional[str], pydantic.Field(alias="arcFactT")] = None

    watt_under_wgal_freq: Annotated[
        Optional[str], pydantic.Field(alias="wattUnderWgalFreq")
    ] = None

    comm_baud_rate: Annotated[Optional[str], pydantic.Field(alias="commBaudRate")] = (
        None
    )

    equip_mode: Annotated[Optional[str], pydantic.Field(alias="equipMode")] = None

    grid_side_inv_meter2: Annotated[
        Optional[str], pydantic.Field(alias="gridSideINVMeter2")
    ] = None

    under_volt1_delay: Annotated[
        Optional[str], pydantic.Field(alias="underVolt1Delay")
    ] = None

    arc_fault_type: Annotated[Optional[str], pydantic.Field(alias="arcFaultType")] = (
        None
    )

    arc_fact_b: Annotated[Optional[str], pydantic.Field(alias="arcFactB")] = None

    normal_upward_slope: Annotated[
        Optional[str], pydantic.Field(alias="normalUpwardSlope")
    ] = None

    arc_fact_c: Annotated[Optional[str], pydantic.Field(alias="arcFactC")] = None

    pf: Optional[str] = None

    arc_fact_d: Annotated[Optional[str], pydantic.Field(alias="arcFactD")] = None

    gen_min_solar: Annotated[Optional[str], pydantic.Field(alias="genMinSolar")] = None

    sell_time2_volt: Annotated[Optional[str], pydantic.Field(alias="sellTime2Volt")] = (
        None
    )

    arc_fact_f: Annotated[Optional[str], pydantic.Field(alias="arcFactF")] = None

    arc_fact_i: Annotated[Optional[str], pydantic.Field(alias="arcFactI")] = None

    ac_volt_low: Annotated[Optional[str], pydantic.Field(alias="acVoltLow")] = None

    gen_signal: Annotated[Optional[str], pydantic.Field(alias="genSignal")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "sellTime1",
                "genTime2on",
                "beep",
                "sellTime2",
                "wattOverExitFreqStopDelay",
                "sellTime5",
                "sellTime6",
                "sellTime3",
                "sellTime4",
                "exMeterCtSwitch",
                "sdChargeOn",
                "lockInVoltVar",
                "time2on",
                "batWarn",
                "wattVarEnable",
                "reconnMinVolt",
                "caFStart",
                "pvMaxLimit",
                "sensorsCheck",
                "underFreq2Delay",
                "varQac2",
                "varQac3",
                "varQac1",
                "wattUnderExitFreq",
                "overVolt1",
                "overVolt2",
                "varQac4",
                "genPeakPower",
                "meterB",
                "eeprom",
                "meterA",
                "comSet",
                "caVoltPressureEnable",
                "meterC",
                "wattUnderFreq1",
                "solarMaxSellPower",
                "acCoupleOnGridSideEnable",
                "thursdayOn",
                "time3On",
                "batteryRestartCap",
                "overFreq1Delay",
                "bmsErrStop",
                "checkTime",
                "acOutputPowerLimit",
                "atsSwitch",
                "pv1SelfCheck",
                "acCurrentUp",
                "rsd",
                "batteryOn",
                "genTime1on",
                "volt12",
                "volt10",
                "volt11",
                "time1on",
                "wattUnderFreq1StartDelay",
                "rcd",
                "chargeVolt",
                "wednesdayOn",
                "mpptMulti",
                "floatVolt",
                "workState",
                "loadMode",
                "sysWorkMode",
                "sn",
                "genCoolingTime",
                "genPeakShaving",
                "offGridImmediatelyOff",
                "sellTime3Volt",
                "sellTime2Pac",
                "current12",
                "time2On",
                "current10",
                "current11",
                "batteryEfficiency",
                "genAndGridSignal",
                "pv3SelfCheck",
                "wattV4",
                "acFreqLow",
                "wattV2",
                "wattV3",
                "wattV1",
                "batteryEmptyV",
                "open",
                "reconnMaxFreq",
                "standard",
                "wattVarReactive2",
                "disableFloatCharge",
                "inverterType",
                "wattVarReactive3",
                "wattVarReactive4",
                "solarPSU",
                "fridayOn",
                "wattVarReactive1",
                "time4on",
                "cap6",
                "generatorForcedStart",
                "overLongVolt",
                "cap4",
                "cap5",
                "batteryChargeType",
                "genOffVolt",
                "cap2",
                "cap3",
                "absorptionVolt",
                "genToLoad",
                "mpptNum",
                "underFreq2",
                "underFreq1",
                "wattPfEnable",
                "remoteLock",
                "generatorStartCap",
                "batteryMaxCurrentCharge",
                "overFreq1",
                "tuesdayOn",
                "genOnVolt",
                "overFreq2",
                "solar2WindInputEnable",
                "caVStop",
                "time5On",
                "battMode",
                "allowRemoteControl",
                "genOnCap",
                "gridAlwaysOn",
                "batteryLowVolt",
                "acFreqUp",
                "cap1",
                "chargeLimit",
                "generatorStartVolt",
                "overVolt1Delay",
                "sellTime1Pac",
                "californiaFreqPressureEnable",
                "activePowerControl",
                "batteryRestartVolt",
                "zeroExportPower",
                "overVolt2Delay",
                "equChargeCycle",
                "dischargeCurrent",
                "solarSell",
                "mpptVoltLow",
                "time3on",
                "wattVoltEnable",
                "caFwEnable",
                "maxOperatingTimeOfGen",
                "micExportGridOff",
                "importPower",
                "pvLine",
                "three41",
                "caVwEnable",
                "batteryShutdownVolt",
                "volt3",
                "volt4",
                "volt1",
                "volt2",
                "startVoltUp",
                "volt7",
                "volt8",
                "volt5",
                "sellTime6Pac",
                "volt6",
                "time4On",
                "sellTime4Volt",
                "volt9",
                "facLowProtect",
                "wattOverFreq1",
                "wattPf4",
                "lowNoiseMode",
                "tempco",
                "arcFactFrz",
                "wattPf1",
                "wattPf2",
                "wattPf3",
                "meterSelect",
                "genChargeOn",
                "externalCtRatio",
                "gridMode",
                "sellTime5Pac",
                "lowThrough",
                "drmEnable",
                "pv2SelfCheck",
                "underFreq1Delay",
                "energyMode",
                "ampm",
                "gridPeakShaving",
                "time6on",
                "fac",
                "vacLowProtect",
                "chargeCurrentLimit",
                "caLv3",
                "sundayOn",
                "genTime6on",
                "batteryImpedance",
                "safetyType",
                "varVolt4",
                "varVolt3",
                "varVolt2",
                "specialFunction",
                "varVolt1",
                "mondayOn",
                "commAddr",
                "saturdayOn",
                "dischargeLimit",
                "atsEnable",
                "exMeterCt",
                "overFreq2Delay",
                "phase",
                "autoDim",
                "batteryWorkStatus",
                "genToLoadOn",
                "timeSync",
                "wattOverWgralFreq",
                "sdBatteryCurrent",
                "peakAndVallery",
                "batteryEmptyVolt",
                "batteryLowCap",
                "underVolt2Delay",
                "equChargeTime",
                "battType",
                "gridPeakPower",
                "reset",
                "vacHighProtect",
                "genTime5on",
                "deyeGenPowerDoubleFlag",
                "pwm",
                "time5on",
                "highThrough",
                "lockOutVoltVar",
                "lockInWattPF",
                "caVStart",
                "acVoltUp",
                "wattFreqEnable",
                "wattOverExitFreq",
                "sellTime5Volt",
                "caFStop",
                "lowPowerMode",
                "varVoltEnable",
                "acCoupleFreqUpper",
                "impedanceLow",
                "acType",
                "facHighProtect",
                "recoveryTime",
                "underVolt2",
                "lithiumMode",
                "underVolt1",
                "gridSignal",
                "wattOverFreq1StartDelay",
                "testCommand",
                "time6On",
                "signalIslandModeEnable",
                "upsStandard",
                "reconnMinFreq",
                "parallelRegister2",
                "parallelRegister1",
                "startVoltLow",
                "smartLoadOpenDelay",
                "genTime4on",
                "sellTime1Volt",
                "wattVarActive4",
                "wattVarActive3",
                "genConnectGrid",
                "flag2",
                "softStart",
                "lockOutWattPF",
                "sdStartCap",
                "current4",
                "current3",
                "current2",
                "current1",
                "gfdi",
                "current8",
                "current7",
                "current6",
                "current5",
                "checkSelfTime",
                "limit",
                "wattW3",
                "wattVarActive2",
                "wattW4",
                "wattVarActive1",
                "externalCurrent",
                "wattW1",
                "wattW2",
                "vnResponseTime",
                "batteryShutdownCap",
                "wattUnderExitFreqStopDelay",
                "offset",
                "sellTime4Pac",
                "wattActivePf1",
                "current9",
                "dischargeVolt",
                "qvResponseTime",
                "wattActivePf4",
                "time1On",
                "wattActivePf2",
                "four19",
                "wattActivePf3",
                "micExportAll",
                "batteryMaxCurrentDischarge",
                "isletProtect",
                "lockOutChange",
                "californiaVoltPressureEnable",
                "equVoltCharge",
                "batteryCap",
                "genOffCap",
                "genTime3on",
                "sellTime6Volt",
                "sellTime3Pac",
                "acCoupleOnLoadSideEnable",
                "sdStartVolt",
                "generatorBatteryCurrent",
                "reconnMaxVolt",
                "modbusSn",
                "inverterOutputVoltage",
                "chargeCurrent",
                "solar1WindInputEnable",
                "dcVoltUp",
                "parallel",
                "limter",
                "batErr",
                "backupDelay",
                "dischargeCurrentLimit",
                "arcFactT",
                "wattUnderWgalFreq",
                "commBaudRate",
                "equipMode",
                "gridSideINVMeter2",
                "underVolt1Delay",
                "arcFaultType",
                "arcFactB",
                "normalUpwardSlope",
                "arcFactC",
                "pf",
                "arcFactD",
                "genMinSolar",
                "sellTime2Volt",
                "arcFactF",
                "arcFactI",
                "acVoltLow",
                "genSignal",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    InverterSettings.model_rebuild()
except NameError:
    pass
