"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .realtimevip import RealtimeVip, RealtimeVipTypedDict
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class LoadRealtimeDataTypedDict(TypedDict):
    total_used: NotRequired[float]
    daily_used: NotRequired[float]
    vip: NotRequired[List[RealtimeVipTypedDict]]
    total_power: NotRequired[float]
    smart_load_status: NotRequired[int]
    load_fac: NotRequired[float]
    ups_power_l1: NotRequired[float]
    ups_power_l2: NotRequired[float]
    ups_power_l3: NotRequired[float]
    ups_power_total: NotRequired[float]


class LoadRealtimeData(BaseModel):
    total_used: Annotated[Optional[float], pydantic.Field(alias="totalUsed")] = None

    daily_used: Annotated[Optional[float], pydantic.Field(alias="dailyUsed")] = None

    vip: Optional[List[RealtimeVip]] = None

    total_power: Annotated[Optional[float], pydantic.Field(alias="totalPower")] = None

    smart_load_status: Annotated[
        Optional[int], pydantic.Field(alias="smartLoadStatus")
    ] = None

    load_fac: Annotated[Optional[float], pydantic.Field(alias="loadFac")] = None

    ups_power_l1: Annotated[Optional[float], pydantic.Field(alias="upsPowerL1")] = None

    ups_power_l2: Annotated[Optional[float], pydantic.Field(alias="upsPowerL2")] = None

    ups_power_l3: Annotated[Optional[float], pydantic.Field(alias="upsPowerL3")] = None

    ups_power_total: Annotated[
        Optional[float], pydantic.Field(alias="upsPowerTotal")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "totalUsed",
                "dailyUsed",
                "vip",
                "totalPower",
                "smartLoadStatus",
                "loadFac",
                "upsPowerL1",
                "upsPowerL2",
                "upsPowerL3",
                "upsPowerTotal",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    LoadRealtimeData.model_rebuild()
except NameError:
    pass
