"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 89a97c23fd07

from __future__ import annotations
from .vip import Vip, VipTypedDict
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OutputDataTypedDict(TypedDict):
    vip: NotRequired[List[VipTypedDict]]
    p_inv: NotRequired[float]
    r"""Inverter power (W)"""
    pac: NotRequired[float]
    r"""Output power (W)"""
    fac: NotRequired[float]
    r"""Frequency (Hz)"""


class OutputData(BaseModel):
    vip: Optional[List[Vip]] = None

    p_inv: Annotated[Optional[float], pydantic.Field(alias="pInv")] = None
    r"""Inverter power (W)"""

    pac: Optional[float] = None
    r"""Output power (W)"""

    fac: Optional[float] = None
    r"""Frequency (Hz)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["vip", "pInv", "pac", "fac"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    OutputData.model_rebuild()
except NameError:
    pass
