"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 15f8bc994b16

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


RatesThresholdTypedDict = TypeAliasType("RatesThresholdTypedDict", Union[str, int])
r"""Rate threshold value"""


RatesThreshold = TypeAliasType("RatesThreshold", Union[str, int])
r"""Rate threshold value"""


class PlantIncomeProductTypedDict(TypedDict):
    r"""Energy provider product configuration for Live Price (UK only)"""

    direction: NotRequired[int]
    r"""Energy direction: 1 = export, 0 = import"""
    rates_threshold: NotRequired[RatesThresholdTypedDict]
    r"""Rate threshold value"""
    provider: NotRequired[int]
    r"""Energy provider ID"""
    limit_soc: NotRequired[Nullable[int]]
    r"""State of charge limit (%). Null for export direction."""
    region_id: NotRequired[int]
    r"""Region ID for the energy provider"""


class PlantIncomeProduct(BaseModel):
    r"""Energy provider product configuration for Live Price (UK only)"""

    direction: Optional[int] = None
    r"""Energy direction: 1 = export, 0 = import"""

    rates_threshold: Annotated[
        Optional[RatesThreshold], pydantic.Field(alias="ratesThreshold")
    ] = None
    r"""Rate threshold value"""

    provider: Optional[int] = None
    r"""Energy provider ID"""

    limit_soc: Annotated[OptionalNullable[int], pydantic.Field(alias="limitSoc")] = (
        UNSET
    )
    r"""State of charge limit (%). Null for export direction."""

    region_id: Annotated[Optional[int], pydantic.Field(alias="regionId")] = None
    r"""Region ID for the energy provider"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["direction", "ratesThreshold", "provider", "limitSoc", "regionId"]
        )
        nullable_fields = set(["limitSoc"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PlantIncomeProduct.model_rebuild()
except NameError:
    pass
