"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 026e4f433c53

from __future__ import annotations
from .plantincomecharge import PlantIncomeCharge, PlantIncomeChargeTypedDict
from .plantincomeproduct import PlantIncomeProduct, PlantIncomeProductTypedDict
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PlantIncomeRequestTypedDict(TypedDict):
    id: str
    r"""Plant ID"""
    currency: int
    r"""Currency code"""
    invest: float
    r"""Total investment amount"""
    charges: List[PlantIncomeChargeTypedDict]
    r"""Pricing entries. For Constant Price (type 1): single entry covering 00:00–24:00. For Time of Use (type 2): up to 6 time slots, must start at 00:00 and end at 24:00. For Live Price (type 3, UK only): single entry with empty time ranges."""
    products: NotRequired[List[PlantIncomeProductTypedDict]]
    r"""Energy provider products. Only used with Live Price (type 3, UK only)."""


class PlantIncomeRequest(BaseModel):
    id: str
    r"""Plant ID"""

    currency: int
    r"""Currency code"""

    invest: float
    r"""Total investment amount"""

    charges: List[PlantIncomeCharge]
    r"""Pricing entries. For Constant Price (type 1): single entry covering 00:00–24:00. For Time of Use (type 2): up to 6 time slots, must start at 00:00 and end at 24:00. For Live Price (type 3, UK only): single entry with empty time ranges."""

    products: Optional[List[PlantIncomeProduct]] = None
    r"""Energy provider products. Only used with Live Price (type 3, UK only)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["products"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
