"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 143f6c9fcc3f

from __future__ import annotations
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PlantInfoCurrencyTypedDict(TypedDict):
    id: NotRequired[int]
    code: NotRequired[str]
    r"""Currency code (e.g. GBP)"""
    text: NotRequired[str]
    r"""Currency symbol (e.g. £)"""


class PlantInfoCurrency(BaseModel):
    id: Optional[int] = None

    code: Optional[str] = None
    r"""Currency code (e.g. GBP)"""

    text: Optional[str] = None
    r"""Currency symbol (e.g. £)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "code", "text"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
