"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 148776de54ca

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


PriceTypedDict = TypeAliasType("PriceTypedDict", Union[str, int])
r"""Price per unit of energy. String for types 1 and 2, integer (0) for type 3."""


Price = TypeAliasType("Price", Union[str, int])
r"""Price per unit of energy. String for types 1 and 2, integer (0) for type 3."""


Type2 = Literal[2,]


TypeEnum = Literal[
    "1",
    "3",
]


TypeTypedDict = TypeAliasType("TypeTypedDict", Union[TypeEnum, Type2])
r"""Pricing type: 1 = Constant Price, 2 = Time of Use, 3 = Live Price (UK only)"""


Type = TypeAliasType("Type", Union[TypeEnum, Type2])
r"""Pricing type: 1 = Constant Price, 2 = Time of Use, 3 = Live Price (UK only)"""


class PlantIncomeChargeTypedDict(TypedDict):
    price: NotRequired[PriceTypedDict]
    r"""Price per unit of energy. String for types 1 and 2, integer (0) for type 3."""
    type: NotRequired[TypeTypedDict]
    r"""Pricing type: 1 = Constant Price, 2 = Time of Use, 3 = Live Price (UK only)"""
    start_range: NotRequired[str]
    r"""Start time (HH:MM). Empty string for Live Price."""
    end_range: NotRequired[str]
    r"""End time (HH:MM). Empty string for Live Price."""


class PlantIncomeCharge(BaseModel):
    price: Optional[Price] = None
    r"""Price per unit of energy. String for types 1 and 2, integer (0) for type 3."""

    type: Optional[Type] = None
    r"""Pricing type: 1 = Constant Price, 2 = Time of Use, 3 = Live Price (UK only)"""

    start_range: Annotated[Optional[str], pydantic.Field(alias="startRange")] = None
    r"""Start time (HH:MM). Empty string for Live Price."""

    end_range: Annotated[Optional[str], pydantic.Field(alias="endRange")] = None
    r"""End time (HH:MM). Empty string for Live Price."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["price", "type", "startRange", "endRange"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlantIncomeCharge.model_rebuild()
except NameError:
    pass
