"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e3917d1f3485

from __future__ import annotations
from .plantinfocurrency import PlantInfoCurrency, PlantInfoCurrencyTypedDict
from datetime import datetime
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlantInfoRealtimeTypedDict(TypedDict):
    r"""Real-time energy and financial data for the plant"""

    pac: NotRequired[float]
    r"""Current power (W)"""
    efficiency: NotRequired[float]
    etoday: NotRequired[float]
    r"""Energy generated today (kWh)"""
    emonth: NotRequired[float]
    r"""Energy generated this month (kWh)"""
    eyear: NotRequired[float]
    r"""Energy generated this year (kWh)"""
    etotal: NotRequired[float]
    r"""Total energy generated (kWh)"""
    total_power: NotRequired[float]
    r"""Total power capacity (kW)"""
    currency: NotRequired[PlantInfoCurrencyTypedDict]
    invest: NotRequired[float]
    income: NotRequired[float]
    r"""Income amount"""
    update_at: NotRequired[datetime]


class PlantInfoRealtime(BaseModel):
    r"""Real-time energy and financial data for the plant"""

    pac: Optional[float] = None
    r"""Current power (W)"""

    efficiency: Optional[float] = None

    etoday: Optional[float] = None
    r"""Energy generated today (kWh)"""

    emonth: Optional[float] = None
    r"""Energy generated this month (kWh)"""

    eyear: Optional[float] = None
    r"""Energy generated this year (kWh)"""

    etotal: Optional[float] = None
    r"""Total energy generated (kWh)"""

    total_power: Annotated[Optional[float], pydantic.Field(alias="totalPower")] = None
    r"""Total power capacity (kW)"""

    currency: Optional[PlantInfoCurrency] = None

    invest: Optional[float] = None

    income: Optional[float] = None
    r"""Income amount"""

    update_at: Annotated[Optional[datetime], pydantic.Field(alias="updateAt")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "pac",
                "efficiency",
                "etoday",
                "emonth",
                "eyear",
                "etotal",
                "totalPower",
                "currency",
                "invest",
                "income",
                "updateAt",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlantInfoRealtime.model_rebuild()
except NameError:
    pass
