"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e0c3c6c72559

from __future__ import annotations
from .plantinfocharge import PlantInfoCharge, PlantInfoChargeTypedDict
from .plantinfocurrency import PlantInfoCurrency, PlantInfoCurrencyTypedDict
from .plantinfomaster import PlantInfoMaster, PlantInfoMasterTypedDict
from .plantinfoproduct import PlantInfoProduct, PlantInfoProductTypedDict
from .plantinforealtime import PlantInfoRealtime, PlantInfoRealtimeTypedDict
from .plantinfotimezone import PlantInfoTimezone, PlantInfoTimezoneTypedDict
from datetime import datetime
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FluxProductsTypedDict(TypedDict):
    pass


class FluxProducts(BaseModel):
    pass


class EpexProductTypedDict(TypedDict):
    pass


class EpexProduct(BaseModel):
    pass


class PlantInfoTypedDict(TypedDict):
    id: NotRequired[int]
    r"""Plant ID"""
    name: NotRequired[str]
    r"""Plant name"""
    total_power: NotRequired[float]
    r"""Total power capacity (kW)"""
    thumb_url: NotRequired[str]
    r"""Thumbnail image URL"""
    join_date: NotRequired[datetime]
    r"""Date the plant was registered"""
    type: NotRequired[int]
    r"""Plant type"""
    status: NotRequired[int]
    r"""Plant status"""
    charges: NotRequired[List[PlantInfoChargeTypedDict]]
    r"""Current electricity pricing charges (half-hourly slots for Live Price type 3)"""
    products: NotRequired[Nullable[List[PlantInfoProductTypedDict]]]
    r"""Energy provider products (present for Live Price type 3)"""
    lon: NotRequired[float]
    r"""Longitude"""
    lat: NotRequired[float]
    r"""Latitude"""
    address: NotRequired[str]
    r"""Plant address"""
    master: NotRequired[PlantInfoMasterTypedDict]
    currency: NotRequired[PlantInfoCurrencyTypedDict]
    timezone: NotRequired[PlantInfoTimezoneTypedDict]
    realtime: NotRequired[PlantInfoRealtimeTypedDict]
    r"""Real-time energy and financial data for the plant"""
    create_at: NotRequired[datetime]
    phone: NotRequired[str]
    email: NotRequired[str]
    installer: NotRequired[str]
    principal: NotRequired[str]
    plant_permission: NotRequired[List[str]]
    r"""List of permission strings for this plant"""
    flux_products: NotRequired[Nullable[FluxProductsTypedDict]]
    product_warranty_registered: NotRequired[int]
    ct_enable: NotRequired[int]
    invest: NotRequired[float]
    r"""Total investment amount"""
    epex_product: NotRequired[Nullable[EpexProductTypedDict]]


class PlantInfo(BaseModel):
    id: Optional[int] = None
    r"""Plant ID"""

    name: Optional[str] = None
    r"""Plant name"""

    total_power: Annotated[Optional[float], pydantic.Field(alias="totalPower")] = None
    r"""Total power capacity (kW)"""

    thumb_url: Annotated[Optional[str], pydantic.Field(alias="thumbUrl")] = None
    r"""Thumbnail image URL"""

    join_date: Annotated[Optional[datetime], pydantic.Field(alias="joinDate")] = None
    r"""Date the plant was registered"""

    type: Optional[int] = None
    r"""Plant type"""

    status: Optional[int] = None
    r"""Plant status"""

    charges: Optional[List[PlantInfoCharge]] = None
    r"""Current electricity pricing charges (half-hourly slots for Live Price type 3)"""

    products: OptionalNullable[List[PlantInfoProduct]] = UNSET
    r"""Energy provider products (present for Live Price type 3)"""

    lon: Optional[float] = None
    r"""Longitude"""

    lat: Optional[float] = None
    r"""Latitude"""

    address: Optional[str] = None
    r"""Plant address"""

    master: Optional[PlantInfoMaster] = None

    currency: Optional[PlantInfoCurrency] = None

    timezone: Optional[PlantInfoTimezone] = None

    realtime: Optional[PlantInfoRealtime] = None
    r"""Real-time energy and financial data for the plant"""

    create_at: Annotated[Optional[datetime], pydantic.Field(alias="createAt")] = None

    phone: Optional[str] = None

    email: Optional[str] = None

    installer: Optional[str] = None

    principal: Optional[str] = None

    plant_permission: Annotated[
        Optional[List[str]], pydantic.Field(alias="plantPermission")
    ] = None
    r"""List of permission strings for this plant"""

    flux_products: Annotated[
        OptionalNullable[FluxProducts], pydantic.Field(alias="fluxProducts")
    ] = UNSET

    product_warranty_registered: Annotated[
        Optional[int], pydantic.Field(alias="productWarrantyRegistered")
    ] = None

    ct_enable: Annotated[Optional[int], pydantic.Field(alias="ctEnable")] = None

    invest: Optional[float] = None
    r"""Total investment amount"""

    epex_product: Annotated[
        OptionalNullable[EpexProduct], pydantic.Field(alias="epexProduct")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "totalPower",
                "thumbUrl",
                "joinDate",
                "type",
                "status",
                "charges",
                "products",
                "lon",
                "lat",
                "address",
                "master",
                "currency",
                "timezone",
                "realtime",
                "createAt",
                "phone",
                "email",
                "installer",
                "principal",
                "plantPermission",
                "fluxProducts",
                "productWarrantyRegistered",
                "ctEnable",
                "invest",
                "epexProduct",
            ]
        )
        nullable_fields = set(["products", "fluxProducts", "epexProduct"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PlantInfo.model_rebuild()
except NameError:
    pass
