"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gatewayinfo import GatewayInfo, GatewayInfoTypedDict
from .inverterversion import InverterVersion, InverterVersionTypedDict
from .plantsummary import PlantSummary, PlantSummaryTypedDict
from datetime import datetime
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlantInverterInfoTypedDict(TypedDict):
    id: NotRequired[int]
    sn: NotRequired[str]
    alias: NotRequired[str]
    gsn: NotRequired[str]
    status: NotRequired[int]
    type: NotRequired[int]
    comm_type_name: NotRequired[str]
    cust_code: NotRequired[int]
    version: NotRequired[InverterVersionTypedDict]
    model: NotRequired[str]
    pac: NotRequired[float]
    etoday: NotRequired[float]
    etotal: NotRequired[float]
    update_at: NotRequired[datetime]
    opened: NotRequired[int]
    plant: NotRequired[PlantSummaryTypedDict]
    gateway_vo: NotRequired[GatewayInfoTypedDict]
    sunsynk_equip: NotRequired[bool]
    protocol_identifier: NotRequired[str]


class PlantInverterInfo(BaseModel):
    id: Optional[int] = None

    sn: Optional[str] = None

    alias: Optional[str] = None

    gsn: Optional[str] = None

    status: Optional[int] = None

    type: Optional[int] = None

    comm_type_name: Annotated[Optional[str], pydantic.Field(alias="commTypeName")] = (
        None
    )

    cust_code: Annotated[Optional[int], pydantic.Field(alias="custCode")] = None

    version: Optional[InverterVersion] = None

    model: Optional[str] = None

    pac: Optional[float] = None

    etoday: Optional[float] = None

    etotal: Optional[float] = None

    update_at: Annotated[Optional[datetime], pydantic.Field(alias="updateAt")] = None

    opened: Optional[int] = None

    plant: Optional[PlantSummary] = None

    gateway_vo: Annotated[Optional[GatewayInfo], pydantic.Field(alias="gatewayVO")] = (
        None
    )

    sunsynk_equip: Annotated[Optional[bool], pydantic.Field(alias="sunsynkEquip")] = (
        None
    )

    protocol_identifier: Annotated[
        Optional[str], pydantic.Field(alias="protocolIdentifier")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "sn",
                "alias",
                "gsn",
                "status",
                "type",
                "commTypeName",
                "custCode",
                "version",
                "model",
                "pac",
                "etoday",
                "etotal",
                "updateAt",
                "opened",
                "plant",
                "gatewayVO",
                "sunsynkEquip",
                "protocolIdentifier",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlantInverterInfo.model_rebuild()
except NameError:
    pass
