"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 0e26a537fb7a

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlantInfoProductTypedDict(TypedDict):
    r"""Energy provider product in plant info response"""

    direction: NotRequired[int]
    r"""1 = export, 0 = import"""
    rates_threshold: NotRequired[float]
    limit_soc: NotRequired[Nullable[int]]
    r"""State of charge limit (%). Null for export."""
    provider: NotRequired[int]
    r"""Energy provider ID"""
    region_id: NotRequired[int]
    r"""Region ID"""


class PlantInfoProduct(BaseModel):
    r"""Energy provider product in plant info response"""

    direction: Optional[int] = None
    r"""1 = export, 0 = import"""

    rates_threshold: Annotated[
        Optional[float], pydantic.Field(alias="ratesThreshold")
    ] = None

    limit_soc: Annotated[OptionalNullable[int], pydantic.Field(alias="limitSoc")] = (
        UNSET
    )
    r"""State of charge limit (%). Null for export."""

    provider: Optional[int] = None
    r"""Energy provider ID"""

    region_id: Annotated[Optional[int], pydantic.Field(alias="regionId")] = None
    r"""Region ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["direction", "ratesThreshold", "limitSoc", "provider", "regionId"]
        )
        nullable_fields = set(["limitSoc"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PlantInfoProduct.model_rebuild()
except NameError:
    pass
