"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PvTypedDict(TypedDict):
    pass


class Pv(BaseModel):
    pass


class PlantFlowDataTypedDict(TypedDict):
    cust_code: NotRequired[int]
    protocol_identifier: NotRequired[str]
    meter_code: NotRequired[int]
    pv_power: NotRequired[float]
    batt_power: NotRequired[float]
    batt_power2: NotRequired[float]
    grid_or_meter_power: NotRequired[float]
    load_or_eps_power: NotRequired[float]
    gen_power: NotRequired[float]
    min_power: NotRequired[float]
    soc: NotRequired[float]
    smart_load_power: NotRequired[float]
    ups_load_power: NotRequired[float]
    home_load_power: NotRequired[float]
    charge_pile_power: NotRequired[float]
    pv_to: NotRequired[bool]
    to_load: NotRequired[bool]
    to_smart_load: NotRequired[bool]
    to_ups_load: NotRequired[bool]
    to_home_load: NotRequired[bool]
    to_grid: NotRequired[bool]
    to_bat: NotRequired[bool]
    bat_to: NotRequired[bool]
    grid_to: NotRequired[bool]
    gen_to: NotRequired[bool]
    min_to: NotRequired[bool]
    to_charge_pile: NotRequired[bool]
    exists_gen: NotRequired[bool]
    exists_min: NotRequired[bool]
    exists_grid: NotRequired[bool]
    gen_on: NotRequired[bool]
    micro_on: NotRequired[bool]
    exists_meter: NotRequired[bool]
    bms_comm_fault_flag: NotRequired[bool]
    exists_three_load: NotRequired[bool]
    exists_smart_load: NotRequired[bool]
    exists_charge_pile: NotRequired[bool]
    pv: NotRequired[Nullable[PvTypedDict]]
    exist_think_power: NotRequired[bool]
    time: NotRequired[Nullable[datetime]]


class PlantFlowData(BaseModel):
    cust_code: Annotated[Optional[int], pydantic.Field(alias="custCode")] = None

    protocol_identifier: Annotated[
        Optional[str], pydantic.Field(alias="protocolIdentifier")
    ] = None

    meter_code: Annotated[Optional[int], pydantic.Field(alias="meterCode")] = None

    pv_power: Annotated[Optional[float], pydantic.Field(alias="pvPower")] = None

    batt_power: Annotated[Optional[float], pydantic.Field(alias="battPower")] = None

    batt_power2: Annotated[Optional[float], pydantic.Field(alias="battPower2")] = None

    grid_or_meter_power: Annotated[
        Optional[float], pydantic.Field(alias="gridOrMeterPower")
    ] = None

    load_or_eps_power: Annotated[
        Optional[float], pydantic.Field(alias="loadOrEpsPower")
    ] = None

    gen_power: Annotated[Optional[float], pydantic.Field(alias="genPower")] = None

    min_power: Annotated[Optional[float], pydantic.Field(alias="minPower")] = None

    soc: Optional[float] = None

    smart_load_power: Annotated[
        Optional[float], pydantic.Field(alias="smartLoadPower")
    ] = None

    ups_load_power: Annotated[Optional[float], pydantic.Field(alias="upsLoadPower")] = (
        None
    )

    home_load_power: Annotated[
        Optional[float], pydantic.Field(alias="homeLoadPower")
    ] = None

    charge_pile_power: Annotated[
        Optional[float], pydantic.Field(alias="chargePilePower")
    ] = None

    pv_to: Annotated[Optional[bool], pydantic.Field(alias="pvTo")] = None

    to_load: Annotated[Optional[bool], pydantic.Field(alias="toLoad")] = None

    to_smart_load: Annotated[Optional[bool], pydantic.Field(alias="toSmartLoad")] = None

    to_ups_load: Annotated[Optional[bool], pydantic.Field(alias="toUpsLoad")] = None

    to_home_load: Annotated[Optional[bool], pydantic.Field(alias="toHomeLoad")] = None

    to_grid: Annotated[Optional[bool], pydantic.Field(alias="toGrid")] = None

    to_bat: Annotated[Optional[bool], pydantic.Field(alias="toBat")] = None

    bat_to: Annotated[Optional[bool], pydantic.Field(alias="batTo")] = None

    grid_to: Annotated[Optional[bool], pydantic.Field(alias="gridTo")] = None

    gen_to: Annotated[Optional[bool], pydantic.Field(alias="genTo")] = None

    min_to: Annotated[Optional[bool], pydantic.Field(alias="minTo")] = None

    to_charge_pile: Annotated[Optional[bool], pydantic.Field(alias="toChargePile")] = (
        None
    )

    exists_gen: Annotated[Optional[bool], pydantic.Field(alias="existsGen")] = None

    exists_min: Annotated[Optional[bool], pydantic.Field(alias="existsMin")] = None

    exists_grid: Annotated[Optional[bool], pydantic.Field(alias="existsGrid")] = None

    gen_on: Annotated[Optional[bool], pydantic.Field(alias="genOn")] = None

    micro_on: Annotated[Optional[bool], pydantic.Field(alias="microOn")] = None

    exists_meter: Annotated[Optional[bool], pydantic.Field(alias="existsMeter")] = None

    bms_comm_fault_flag: Annotated[
        Optional[bool], pydantic.Field(alias="bmsCommFaultFlag")
    ] = None

    exists_three_load: Annotated[
        Optional[bool], pydantic.Field(alias="existsThreeLoad")
    ] = None

    exists_smart_load: Annotated[
        Optional[bool], pydantic.Field(alias="existsSmartLoad")
    ] = None

    exists_charge_pile: Annotated[
        Optional[bool], pydantic.Field(alias="existsChargePile")
    ] = None

    pv: OptionalNullable[Pv] = UNSET

    exist_think_power: Annotated[
        Optional[bool], pydantic.Field(alias="existThinkPower")
    ] = None

    time: OptionalNullable[datetime] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "custCode",
                "protocolIdentifier",
                "meterCode",
                "pvPower",
                "battPower",
                "battPower2",
                "gridOrMeterPower",
                "loadOrEpsPower",
                "genPower",
                "minPower",
                "soc",
                "smartLoadPower",
                "upsLoadPower",
                "homeLoadPower",
                "chargePilePower",
                "pvTo",
                "toLoad",
                "toSmartLoad",
                "toUpsLoad",
                "toHomeLoad",
                "toGrid",
                "toBat",
                "batTo",
                "gridTo",
                "genTo",
                "minTo",
                "toChargePile",
                "existsGen",
                "existsMin",
                "existsGrid",
                "genOn",
                "microOn",
                "existsMeter",
                "bmsCommFaultFlag",
                "existsThreeLoad",
                "existsSmartLoad",
                "existsChargePile",
                "pv",
                "existThinkPower",
                "time",
            ]
        )
        nullable_fields = set(["pv", "time"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PlantFlowData.model_rebuild()
except NameError:
    pass
