"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PlantSummaryTypedDict(TypedDict):
    id: NotRequired[int]
    name: NotRequired[str]
    type: NotRequired[str]
    master: NotRequired[str]
    installer: NotRequired[str]
    email: NotRequired[str]
    phone: NotRequired[str]


class PlantSummary(BaseModel):
    id: Optional[int] = None

    name: Optional[str] = None

    type: Optional[str] = None

    master: Optional[str] = None

    installer: Optional[str] = None

    email: Optional[str] = None

    phone: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["id", "name", "type", "master", "installer", "email", "phone"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
