"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .plantinvertersdata import PlantInvertersData, PlantInvertersDataTypedDict
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PlantInvertersResponseTypedDict(TypedDict):
    success: NotRequired[bool]
    code: NotRequired[int]
    msg: NotRequired[str]
    data: NotRequired[PlantInvertersDataTypedDict]


class PlantInvertersResponse(BaseModel):
    success: Optional[bool] = None

    code: Optional[int] = None

    msg: Optional[str] = None

    data: Optional[PlantInvertersData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "code", "msg", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
