"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 9458a3597d78

from __future__ import annotations
from datetime import datetime
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


Status = Union[
    Literal[
        "import",
        "export",
    ],
    UnrecognizedStr,
]
r"""Energy direction for this charge"""


class PlantInfoChargeTypedDict(TypedDict):
    r"""A pricing charge entry returned in the plant info response"""

    id: NotRequired[int]
    start_range: NotRequired[str]
    r"""Start time (HH:MM)"""
    end_range: NotRequired[str]
    r"""End time (HH:MM)"""
    price: NotRequired[float]
    r"""Price per unit"""
    type: NotRequired[int]
    r"""Pricing type: 1 = Constant, 2 = Time of Use, 3 = Live Price"""
    station_id: NotRequired[int]
    r"""Plant/station ID"""
    create_at: NotRequired[datetime]
    status: NotRequired[Status]
    r"""Energy direction for this charge"""


class PlantInfoCharge(BaseModel):
    r"""A pricing charge entry returned in the plant info response"""

    id: Optional[int] = None

    start_range: Annotated[Optional[str], pydantic.Field(alias="startRange")] = None
    r"""Start time (HH:MM)"""

    end_range: Annotated[Optional[str], pydantic.Field(alias="endRange")] = None
    r"""End time (HH:MM)"""

    price: Optional[float] = None
    r"""Price per unit"""

    type: Optional[int] = None
    r"""Pricing type: 1 = Constant, 2 = Time of Use, 3 = Live Price"""

    station_id: Annotated[Optional[int], pydantic.Field(alias="stationId")] = None
    r"""Plant/station ID"""

    create_at: Annotated[Optional[datetime], pydantic.Field(alias="createAt")] = None

    status: Optional[Status] = None
    r"""Energy direction for this charge"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "startRange",
                "endRange",
                "price",
                "type",
                "stationId",
                "createAt",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlantInfoCharge.model_rebuild()
except NameError:
    pass
