"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlantTypedDict(TypedDict):
    id: NotRequired[int]
    r"""Plant ID"""
    name: NotRequired[str]
    r"""Plant name"""
    thumb_url: NotRequired[str]
    r"""Thumbnail URL"""
    status: NotRequired[float]
    r"""Plant status"""
    address: NotRequired[str]
    r"""Plant address"""
    pac: NotRequired[float]
    r"""Current power"""
    efficiency: NotRequired[float]
    r"""Efficiency percentage"""
    etoday: NotRequired[float]
    r"""Energy generated today (kWh)"""
    etotal: NotRequired[float]
    r"""Total energy generated (kWh)"""
    update_at: NotRequired[datetime]
    r"""Last update timestamp"""
    create_at: NotRequired[datetime]
    r"""Creation timestamp"""
    type: NotRequired[float]
    r"""Plant type"""
    master_id: NotRequired[int]
    r"""Master ID"""
    share: NotRequired[bool]
    r"""Share settings"""
    plant_permission: NotRequired[List[str]]
    exist_camera: NotRequired[bool]
    r"""Whether camera exists"""


class Plant(BaseModel):
    id: Optional[int] = None
    r"""Plant ID"""

    name: Optional[str] = None
    r"""Plant name"""

    thumb_url: Annotated[Optional[str], pydantic.Field(alias="thumbUrl")] = None
    r"""Thumbnail URL"""

    status: Optional[float] = None
    r"""Plant status"""

    address: Optional[str] = None
    r"""Plant address"""

    pac: Optional[float] = None
    r"""Current power"""

    efficiency: Optional[float] = None
    r"""Efficiency percentage"""

    etoday: Optional[float] = None
    r"""Energy generated today (kWh)"""

    etotal: Optional[float] = None
    r"""Total energy generated (kWh)"""

    update_at: Annotated[Optional[datetime], pydantic.Field(alias="updateAt")] = None
    r"""Last update timestamp"""

    create_at: Annotated[Optional[datetime], pydantic.Field(alias="createAt")] = None
    r"""Creation timestamp"""

    type: Optional[float] = None
    r"""Plant type"""

    master_id: Annotated[Optional[int], pydantic.Field(alias="masterId")] = None
    r"""Master ID"""

    share: Optional[bool] = None
    r"""Share settings"""

    plant_permission: Annotated[
        Optional[List[str]], pydantic.Field(alias="plantPermission")
    ] = None

    exist_camera: Annotated[Optional[bool], pydantic.Field(alias="existCamera")] = None
    r"""Whether camera exists"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "thumbUrl",
                "status",
                "address",
                "pac",
                "efficiency",
                "etoday",
                "etotal",
                "updateAt",
                "createAt",
                "type",
                "masterId",
                "share",
                "plantPermission",
                "existCamera",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Plant.model_rebuild()
except NameError:
    pass
