"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .plantinverterinfo import PlantInverterInfo, PlantInverterInfoTypedDict
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlantInvertersDataTypedDict(TypedDict):
    page_size: NotRequired[int]
    page_number: NotRequired[int]
    total: NotRequired[int]
    infos: NotRequired[List[PlantInverterInfoTypedDict]]


class PlantInvertersData(BaseModel):
    page_size: Annotated[Optional[int], pydantic.Field(alias="pageSize")] = None

    page_number: Annotated[Optional[int], pydantic.Field(alias="pageNumber")] = None

    total: Optional[int] = None

    infos: Optional[List[PlantInverterInfo]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["pageSize", "pageNumber", "total", "infos"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlantInvertersData.model_rebuild()
except NameError:
    pass
