"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PvIvTypedDict(TypedDict):
    id: NotRequired[int]
    pv_no: NotRequired[int]
    r"""PV string number"""
    vpv: NotRequired[float]
    r"""PV voltage (V)"""
    ipv: NotRequired[float]
    r"""PV current (A)"""
    ppv: NotRequired[float]
    r"""PV power (kW)"""
    today_pv: NotRequired[float]
    r"""Today's PV energy (kWh)"""
    sn: NotRequired[str]
    r"""Serial number"""
    time: NotRequired[datetime]
    r"""Record timestamp"""


class PvIv(BaseModel):
    id: Optional[int] = None

    pv_no: Annotated[Optional[int], pydantic.Field(alias="pvNo")] = None
    r"""PV string number"""

    vpv: Optional[float] = None
    r"""PV voltage (V)"""

    ipv: Optional[float] = None
    r"""PV current (A)"""

    ppv: Optional[float] = None
    r"""PV power (kW)"""

    today_pv: Annotated[Optional[float], pydantic.Field(alias="todayPv")] = None
    r"""Today's PV energy (kWh)"""

    sn: Optional[str] = None
    r"""Serial number"""

    time: Optional[datetime] = None
    r"""Record timestamp"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["id", "pvNo", "vpv", "ipv", "ppv", "todayPv", "sn", "time"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PvIv.model_rebuild()
except NameError:
    pass
