"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: cc1bb354ea23

from __future__ import annotations
from .invertersettingsset import InverterSettingsSet, InverterSettingsSetTypedDict
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from sunsynk_api_client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SetInverterSettingsRequestTypedDict(TypedDict):
    sn_param: str
    body: InverterSettingsSetTypedDict


class SetInverterSettingsRequest(BaseModel):
    sn_param: Annotated[
        str,
        pydantic.Field(alias="sn"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        InverterSettingsSet,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class SetInverterSettingsResponseTypedDict(TypedDict):
    r"""Settings updated successfully"""

    msg: NotRequired[str]
    code: NotRequired[int]


class SetInverterSettingsResponse(BaseModel):
    r"""Settings updated successfully"""

    msg: Optional[str] = None

    code: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["msg", "code"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
