"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d0d7872bd965

from __future__ import annotations
from .plantincomerequest import PlantIncomeRequest, PlantIncomeRequestTypedDict
import pydantic
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from sunsynk_api_client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SetPlantIncomeRequestTypedDict(TypedDict):
    plant_id: str
    body: PlantIncomeRequestTypedDict


class SetPlantIncomeRequest(BaseModel):
    plant_id: Annotated[
        str,
        pydantic.Field(alias="plantId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        PlantIncomeRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class SetPlantIncomeResponseTypedDict(TypedDict):
    r"""Income pricing updated successfully"""

    msg: NotRequired[str]
    code: NotRequired[int]


class SetPlantIncomeResponse(BaseModel):
    r"""Income pricing updated successfully"""

    msg: Optional[str] = None

    code: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["msg", "code"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
