"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sunsynk_api_client.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


GrantType = Literal["password",]


ClientID = Literal["csp-web",]


class TokenRequestTypedDict(TypedDict):
    username: str
    r"""User's username"""
    password: str
    r"""User's password"""
    grant_type: GrantType
    client_id: ClientID


class TokenRequest(BaseModel):
    username: str
    r"""User's username"""

    password: str
    r"""User's password"""

    grant_type: GrantType

    client_id: ClientID
