"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TokenResponseDataTypedDict(TypedDict):
    access_token: NotRequired[str]
    refresh_token: NotRequired[str]
    expires_in: NotRequired[int]
    token_type: NotRequired[str]


class TokenResponseData(BaseModel):
    access_token: Optional[str] = None

    refresh_token: Optional[str] = None

    expires_in: Optional[int] = None

    token_type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["access_token", "refresh_token", "expires_in", "token_type"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TokenResponseTypedDict(TypedDict):
    success: NotRequired[bool]
    data: NotRequired[TokenResponseDataTypedDict]


class TokenResponse(BaseModel):
    success: Optional[bool] = None

    data: Optional[TokenResponseData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
