"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class VipTypedDict(TypedDict):
    voltage: NotRequired[float]
    r"""Voltage (V)"""
    current: NotRequired[float]
    r"""Current (A)"""
    power: NotRequired[float]
    r"""Power (kW)"""


class Vip(BaseModel):
    voltage: Optional[float] = None
    r"""Voltage (V)"""

    current: Optional[float] = None
    r"""Current (A)"""

    power: Optional[float] = None
    r"""Power (kW)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["voltage", "current", "power"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
