"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 2f2eb5af586e

from __future__ import annotations
from pydantic import model_serializer
from sunsynk_api_client.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class VipTypedDict(TypedDict):
    volt: NotRequired[str]
    r"""Voltage (V) — returned as a stringified number by the API (e.g. \"236.6\")"""
    current: NotRequired[str]
    r"""Current (A) — returned as a stringified number by the API (e.g. \"0.9\")"""
    power: NotRequired[float]
    r"""Power (W)"""


class Vip(BaseModel):
    volt: Optional[str] = None
    r"""Voltage (V) — returned as a stringified number by the API (e.g. \"236.6\")"""

    current: Optional[str] = None
    r"""Current (A) — returned as a stringified number by the API (e.g. \"0.9\")"""

    power: Optional[float] = None
    r"""Power (W)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["volt", "current", "power"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
