"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .sunsynkerror import SunSynkError
from typing import Any, TYPE_CHECKING

from sunsynk_api_client.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .error import Error, ErrorData
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError
    from .sunsynkdefaulterror import SunSynkDefaultError

__all__ = [
    "Error",
    "ErrorData",
    "NoResponseError",
    "ResponseValidationError",
    "SunSynkDefaultError",
    "SunSynkError",
]

_dynamic_imports: dict[str, str] = {
    "Error": ".error",
    "ErrorData": ".error",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
    "SunSynkDefaultError": ".sunsynkdefaulterror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
