"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4f638efaf76d

import importlib.metadata

__title__: str = "sunsynk-api-client"
__version__: str = "0.3.0"
__openapi_doc_version__: str = "1.3.0"
__gen_version__: str = "2.881.4"
__user_agent__: str = "speakeasy-sdk/python 0.3.0 2.881.4 1.3.0 sunsynk-api-client"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
