"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from sunsynk_api_client import errors, models, utils
from sunsynk_api_client._hooks import HookContext
from sunsynk_api_client.types import OptionalNullable, UNSET
from sunsynk_api_client.utils import get_security_from_env
from sunsynk_api_client.utils.unmarshal_json_response import unmarshal_json_response
from typing import Mapping, Optional


class Inverters(BaseSDK):
    r"""Endpoints for inverter management"""

    def get_api_v1_inverters(
        self,
        *,
        page: Optional[int] = 1,
        limit: Optional[int] = 10,
        total: Optional[int] = 0,
        status: Optional[int] = -1,
        sn: Optional[str] = "",
        plant_id: Optional[str] = "",
        type_: Optional[int] = -2,
        soft_ver: Optional[str] = "",
        hmi_ver: Optional[str] = "",
        agent_company_id: Optional[int] = -1,
        gsn: Optional[str] = "",
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.InvertersResponse:
        r"""Get list of inverters

        Retrieve all inverters associated with the user account

        :param page:
        :param limit:
        :param total:
        :param status:
        :param sn:
        :param plant_id:
        :param type:
        :param soft_ver:
        :param hmi_ver:
        :param agent_company_id:
        :param gsn:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetAPIV1InvertersRequest(
            page=page,
            limit=limit,
            total=total,
            status=status,
            sn=sn,
            plant_id=plant_id,
            type=type_,
            soft_ver=soft_ver,
            hmi_ver=hmi_ver,
            agent_company_id=agent_company_id,
            gsn=gsn,
        )

        req = self._build_request(
            method="GET",
            path="/api/v1/inverters",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_/api/v1/inverters",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.InvertersResponse, http_res)
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SunSynkDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SunSynkDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.SunSynkDefaultError("Unexpected response received", http_res)

    async def get_api_v1_inverters_async(
        self,
        *,
        page: Optional[int] = 1,
        limit: Optional[int] = 10,
        total: Optional[int] = 0,
        status: Optional[int] = -1,
        sn: Optional[str] = "",
        plant_id: Optional[str] = "",
        type_: Optional[int] = -2,
        soft_ver: Optional[str] = "",
        hmi_ver: Optional[str] = "",
        agent_company_id: Optional[int] = -1,
        gsn: Optional[str] = "",
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.InvertersResponse:
        r"""Get list of inverters

        Retrieve all inverters associated with the user account

        :param page:
        :param limit:
        :param total:
        :param status:
        :param sn:
        :param plant_id:
        :param type:
        :param soft_ver:
        :param hmi_ver:
        :param agent_company_id:
        :param gsn:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetAPIV1InvertersRequest(
            page=page,
            limit=limit,
            total=total,
            status=status,
            sn=sn,
            plant_id=plant_id,
            type=type_,
            soft_ver=soft_ver,
            hmi_ver=hmi_ver,
            agent_company_id=agent_company_id,
            gsn=gsn,
        )

        req = self._build_request_async(
            method="GET",
            path="/api/v1/inverters",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_/api/v1/inverters",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.InvertersResponse, http_res)
        if utils.match_response(http_res, ["401", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SunSynkDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SunSynkDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.SunSynkDefaultError("Unexpected response received", http_res)

    def get_plant_inverters(
        self,
        *,
        plant_id: str,
        page: Optional[int] = 1,
        limit: Optional[int] = None,
        status: Optional[str] = "-1",
        type_: Optional[str] = "-2",
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PlantInvertersResponse:
        r"""Get inverters for a plant

        Retrieves list of inverters associated with a specific plant

        :param plant_id:
        :param page:
        :param limit:
        :param status:
        :param type:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetPlantInvertersRequest(
            plant_id=plant_id,
            page=page,
            limit=limit,
            status=status,
            type=type_,
        )

        req = self._build_request(
            method="GET",
            path="/api/v1/plant/{plantId}/inverters",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getPlantInverters",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PlantInvertersResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SunSynkDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SunSynkDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.SunSynkDefaultError("Unexpected response received", http_res)

    async def get_plant_inverters_async(
        self,
        *,
        plant_id: str,
        page: Optional[int] = 1,
        limit: Optional[int] = None,
        status: Optional[str] = "-1",
        type_: Optional[str] = "-2",
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PlantInvertersResponse:
        r"""Get inverters for a plant

        Retrieves list of inverters associated with a specific plant

        :param plant_id:
        :param page:
        :param limit:
        :param status:
        :param type:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetPlantInvertersRequest(
            plant_id=plant_id,
            page=page,
            limit=limit,
            status=status,
            type=type_,
        )

        req = self._build_request_async(
            method="GET",
            path="/api/v1/plant/{plantId}/inverters",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getPlantInverters",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["4XX", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PlantInvertersResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SunSynkDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SunSynkDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.SunSynkDefaultError("Unexpected response received", http_res)
